# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_a_librarian', '0003_auto_20160307_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='askpage',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
