# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 20:38
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask_a_librarian', '0004_askpage_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askpage',
            name='reference_resources',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
