# Generated by Django 2.0.3 on 2018-03-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_a_librarian', '0005_auto_20170926_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_a_librarian_askpage_related', to='units.UnitPage'),
        ),
    ]
