# Generated by Django 2.0.12 on 2020-03-08 03:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ask_a_librarian', '0013_askpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askpage',
            name='intro',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('reusable_content_block', wagtail.blocks.StructBlock([('content', wagtail.snippets.blocks.SnippetChooserBlock('reusable_content.ReusableContent'))])), ('html', wagtail.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='askpage',
            name='reference_resources',
            field=wagtail.fields.RichTextField(blank=True, help_text='Links to guide links and other Ask pages. Make new sections with Header 3'),
        ),
        migrations.AlterField(
            model_name='askpage',
            name='schedule_appointment_page',
            field=models.ForeignKey(blank=True, help_text='Shows up as Schedule icon link. Link to a contact form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
