# Generated by Django 2.0.12 on 2020-03-08 04:32

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask_a_librarian', '0014_auto_20200307_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askpage',
            name='reference_resources',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Links to guide links and other         Ask pages. Make new sections with Header 3'),
        ),
    ]
