# Generated by Django 2.0.12 on 2020-03-08 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_a_librarian', '0015_auto_20200307_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askpage',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Please enter the phone number using the format 773-123-4567', regex='^[0-9]{3}-[0-9]{3}-[0-9]{4}$')], verbose_name='SMS Number'),
        ),
    ]
