# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 19:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('ask_a_librarian', '0021_askpage_rich_text_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='askpage',
            name='schedule_appointment_page',
            field=models.ForeignKey(blank=True, help_text='Link to a contact form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='askpage',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Please enter the phone number using the format 773-123-4567', regex='^[0-9]{3}-[0-9]{3}-[0-9]{4}$')]),
        ),
        migrations.AddField(
            model_name='askpage',
            name='visit_page',
            field=models.ForeignKey(blank=True, help_text='Link to a location or hours page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
