# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_a_librarian', '0022_auto_20160630_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='askpage',
            name='change_to_callout',
            field=models.BooleanField(default=False),
        ),
    ]
