# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('projects', '0001_initial'), ('projects', '0002_auto_20151201_2209'), ('projects', '0003_auto_20151202_1651'), ('projects', '0004_auto_20151203_1806'), ('projects', '0005_auto_20151209_2251'), ('projects', '0006_auto_20160328_1905'), ('projects', '0007_auto_20160610_1600'), ('projects', '0008_auto_20161103_1604'), ('projects', '0009_auto_20161104_1314')]

    initial = True

    dependencies = [
        ('wagtailcore', '0020_add_index_on_page_first_published_at'),
        ('staff', '0000_manual_pre_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('last_reviewed', models.DateField(blank=True, null=True, verbose_name='Last Reviewed')),
                ('description', models.TextField()),
                ('requestor', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('discussion', 'Discussion')], default='active', max_length=55)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=55)),
                ('staff', models.CharField(blank=True, max_length=255)),
                ('date_added_to_list', models.DateField(default=django.utils.timezone.now)),
                ('completion', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_projectpage_editor', to='staff.StaffPage')),
                ('page_maintainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_projectpage_maintainer', to='staff.StaffPage')),
                ('show_sidebar', models.BooleanField(default=False)),
                ('start_sidebar_from_here', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_projectindexpage_editor', to='staff.StaffPage'),
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='last_reviewed',
            field=models.DateField(blank=True, null=True, verbose_name='Last Reviewed'),
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_projectindexpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='show_sidebar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='start_sidebar_from_here',
            field=models.BooleanField(default=False),
        ),
    ]
