# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20151209_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectindexpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_projectindexpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='projectindexpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_projectindexpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_projectpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_projectpage_maintainer', to='staff.StaffPage'),
        ),
    ]
