language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

test:
  adapter: sqlite3
  database: ":memory:"

# command to run tests
script: python manage.py test
