language: python

dist: xenial

python:
  - "3.5"
  - "3.6"

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.7.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.7.deb && sudo service elasticsearch restart

# command to install dependencies
install: "pip install -r requirements.txt"

services:
  - redis-server

# command to run tests
script: python manage.py test
