# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 18:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('wagtaildocs', '0004_capitalizeverbose'),
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePageMainRegistrationLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': 'Additional Registration Links',
                'verbose_name': 'Additional Registration Link',
            },
        ),
        migrations.AlterField(
            model_name='conferencepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Banners should be 1200xB pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='conferencepage',
            name='branding_color',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Please enter a hex color, e.g. #012043', regex='^#[a-zA-Z0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='conferencepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='conferencepage',
            name='tagline',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='conferencepagemainregistrationlinks',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_registration', to='conferences.ConferencePage'),
        ),
    ]
