# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_conferencepagemainregistrationlinks_link_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencepagemainregistrationlinks',
            name='link_text',
        ),
        migrations.AddField(
            model_name='conferencepagemainregistrationlinks',
            name='button_text',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
