# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_auto_20160202_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepagemainregistrationlinks',
            name='button_text',
            field=models.CharField(max_length=20),
        ),
    ]
