# Generated by Django 2.0.3 on 2018-03-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_auto_20170926_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceindexpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferenceindexpage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='conferencepage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferencepage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='conferencesubpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferencesubpage_related', to='units.UnitPage'),
        ),
    ]
