# Generated by Django 2.0.12 on 2019-09-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_auto_20190801_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceindexpage',
            name='news_feed_url',
        ),
        migrations.RemoveField(
            model_name='conferencepage',
            name='news_feed_url',
        ),
        migrations.RemoveField(
            model_name='conferencesubpage',
            name='news_feed_url',
        ),
    ]
