# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0016_auto_20160204_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencepage',
            name='inactive',
        ),
        migrations.AddField(
            model_name='conferencepage',
            name='current',
            field=models.BooleanField(default=True, help_text='Uncheck this when the conference has transpired'),
        ),
    ]
