# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0017_auto_20160205_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencepage',
            name='facebook_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='conferencepage',
            name='hashtag',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='conferencepage',
            name='hashtag_page',
            field=models.URLField(blank=True, help_text='Link to twitter page using a hashtag'),
        ),
        migrations.AddField(
            model_name='conferencepage',
            name='twitter_page',
            field=models.URLField(blank=True),
        ),
    ]
