# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0018_auto_20160205_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencepage',
            name='secondary_registration_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conferencepage',
            name='secondary_registration_heading',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
