# Generated by Django 4.1.10 on 2023-07-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0033_auto_20230601_1324"),
        ("staff", "0028_alter_staffpage_bio"),
        ("units", "0015_auto_20220311_1327"),
        ("conferences", "0019_auto_20230601_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conferenceindexpage",
            name="content_specialist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_content_specialist",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferenceindexpage",
            name="editor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_editor",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferenceindexpage",
            name="page_maintainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_maintainer",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferenceindexpage",
            name="unit",
            field=models.ForeignKey(
                limit_choices_to={"display_in_dropdown": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferencepage",
            name="content_specialist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_content_specialist",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferencepage",
            name="editor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_editor",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferencepage",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="public.locationpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferencepage",
            name="page_maintainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_maintainer",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferencepage",
            name="unit",
            field=models.ForeignKey(
                limit_choices_to={"display_in_dropdown": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferencesubpage",
            name="content_specialist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_content_specialist",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferencesubpage",
            name="editor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_editor",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferencesubpage",
            name="page_maintainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_maintainer",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="conferencesubpage",
            name="unit",
            field=models.ForeignKey(
                limit_choices_to={"display_in_dropdown": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
    ]
