# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0004_capitalizeverbose'),
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('conferences', '0021_auto_20160205_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePageSecondaryRegistrationLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('button_text', models.CharField(max_length=20)),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_registration', to='conferences.ConferencePage')),
            ],
            options={
                'verbose_name': 'Additional Registration Link',
                'verbose_name_plural': 'Additional Registration Links',
            },
        ),
        migrations.AlterModelOptions(
            name='conferencepagemainregistrationlinks',
            options={'verbose_name': 'Main Registration Link', 'verbose_name_plural': 'Main Registration Links'},
        ),
        migrations.AlterField(
            model_name='conferencepagemainregistrationlinks',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_registration', to='conferences.ConferencePage'),
        ),
    ]
