# Generated by Django 5.0.10 on 2025-05-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conferences",
            "0022_conferenceindexpage_exclude_from_search_engines_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenceindexpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conferencepage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conferencesubpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
    ]
