# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0023_auto_20160307_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencepage',
            name='blog_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='conferencepage',
            name='instagram_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='conferencepage',
            name='snapchat_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='conferencepage',
            name='tumbler_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='conferencepage',
            name='youtube_page',
            field=models.URLField(blank=True),
        ),
    ]
