# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0024_auto_20160318_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencepage',
            old_name='tumbler_page',
            new_name='tumblr_page',
        ),
    ]
