# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0031_auto_20160609_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceindexpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='conferencepage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='conferencesubpage',
            name='sort_order',
        ),
    ]
