# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0033_auto_20160616_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceindexpage',
            name='display_hours_in_right_sidebar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conferencepage',
            name='display_hours_in_right_sidebar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conferencesubpage',
            name='display_hours_in_right_sidebar',
            field=models.BooleanField(default=False),
        ),
    ]
