# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0036_auto_20160623_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceindexpage',
            name='events_feed_url',
            field=models.URLField(blank=True, help_text='Link to a Tiny Tiny RSS Feed'),
        ),
        migrations.AlterField(
            model_name='conferencepage',
            name='events_feed_url',
            field=models.URLField(blank=True, help_text='Link to a Tiny Tiny RSS Feed'),
        ),
        migrations.AlterField(
            model_name='conferencesubpage',
            name='events_feed_url',
            field=models.URLField(blank=True, help_text='Link to a Tiny Tiny RSS Feed'),
        ),
    ]
