# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0056_auto_20161031_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencepage',
            old_name='branding_color',
            new_name='primary_branding_color',
        ),
    ]
