# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0058_conferencepage_secondary_branding_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferencepagemainregistrationlinks',
            options={'ordering': ['sort_order'], 'verbose_name': 'Main Registration Link', 'verbose_name_plural': 'Main Registration Links'},
        ),
        migrations.AlterModelOptions(
            name='conferencepageorganizers',
            options={'ordering': ['sort_order'], 'verbose_name': 'Organizer', 'verbose_name_plural': 'Organizers'},
        ),
        migrations.AlterModelOptions(
            name='conferencepagesecondaryregistrationlinks',
            options={'ordering': ['sort_order'], 'verbose_name': 'Additional Registration Link', 'verbose_name_plural': 'Additional Registration Links'},
        ),
        migrations.AlterModelOptions(
            name='conferencepagesponsors',
            options={'ordering': ['sort_order'], 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
    ]
