# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0060_auto_20161103_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceindexpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferenceindexpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='conferenceindexpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferenceindexpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='conferenceindexpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferenceindexpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='conferencepage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferencepage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='conferencepage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferencepage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='conferencepage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferencepage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='conferencesubpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferencesubpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='conferencesubpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferencesubpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='conferencesubpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_conferencesubpage_maintainer', to='staff.StaffPage'),
        ),
    ]
