# Generated by Django 5.2.14 on 2026-07-23 16:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0016_alter_newspage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Describe the thumbnail's content and purpose for screen-reader users. Keep it concise. Required when a thumbnail is set.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="excerpt",
            field=wagtail.fields.RichTextField(
                help_text="Shown on the News feed.", null=True
            ),
        ),
    ]
