# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_auto_20160205_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='sticky_until',
            field=models.DateField(blank=True, help_text='While a story is "sticky" it will appear at the top of the news feed with a special background color.', null=True),
        ),
    ]
