# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_auto_20160223_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsindexpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_newsindexpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='newsindexpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_newsindexpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_newspage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_newspage_maintainer', to='staff.StaffPage'),
        ),
    ]
