# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_auto_20160328_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
