# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_auto_20160812_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEmailAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_text', wagtail.core.fields.RichTextField()),
                ('include_in_email_dated', models.DateField(blank=True, help_text='Emails are send automatically via cron. If that process finds an email addition snippet with the appropriate date it will attach it to the message.', null=True)),
            ],
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
    ]
