# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0047_newsemailaddition'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsemailaddition',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
