# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0049_auto_20160906_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsemailaddition',
            old_name='title',
            new_name='name',
        ),
    ]
