# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0051_auto_20160907_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsemailaddition',
            name='include_in_email_dated',
            field=models.DateField(blank=True, help_text='Emails are send automatically via cron. Only email additions with the appropriate date will be attached to messages.', null=True),
        ),
        migrations.AlterField(
            model_name='newsemailaddition',
            name='name',
            field=models.CharField(help_text='Give this snippet a name to help stay organized. This name will appear in the list of snippets, but not in emails.', max_length=255),
        ),
    ]
