# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0052_auto_20160907_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsemailaddition',
            name='is_footer',
            field=models.BooleanField(default=False, help_text='Text to include in the bottom of every email.'),
        ),
        migrations.AddField(
            model_name='newsemailaddition',
            name='is_header',
            field=models.BooleanField(default=False, help_text='Text to include in the top of every email.'),
        ),
    ]
