# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0053_auto_20160908_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsemailaddition',
            old_name='extra_text',
            new_name='text',
        ),
    ]
