# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0054_auto_20160908_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsemailaddition',
            name='is_footer',
        ),
        migrations.RemoveField(
            model_name='newsemailaddition',
            name='is_header',
        ),
        migrations.RemoveField(
            model_name='newsemailaddition',
            name='name',
        ),
        migrations.AlterField(
            model_name='newsemailaddition',
            name='include_in_email_dated',
            field=models.DateField(default=datetime.datetime.now, help_text='Emails are send automatically via cron. Only email additions with the appropriate date will be attached to messages.'),
        ),
    ]
