# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('directory_unit', '0001_initial'), ('directory_unit', '0002_auto_20151208_1739'), ('directory_unit', '0003_unitsupervisor'), ('directory_unit', '0004_auto_20151213_2022')]

    initial = True

    dependencies = [
        ('staff', '0000_manual_pre_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fullName', models.CharField(default='', max_length=1020)),
                ('xmlUrl', models.CharField(max_length=255)),
                ('parentUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory_unit.DirectoryUnit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.StaffPage')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory_unit.DirectoryUnit')),
            ],
        ),
        migrations.AlterModelOptions(
            name='directoryunit',
            options={'ordering': ['fullName']},
        ),
    ]
