# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_unitpage_building'),
        ('intranetunits', '0004_auto_20170705_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='intranetunitspage',
            name='unit_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loop_page', to='units.UnitPage'),
        ),
    ]
