# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetunits', '0005_intranetunitspage_unit_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intranetunitspage',
            name='unit',
        ),
    ]
