# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetunits', '0051_auto_20160609_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intranetunitsindexpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='intranetunitspage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='intranetunitsreportsindexpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='intranetunitsreportspage',
            name='sort_order',
        ),
    ]
