# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 20:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial_squashed_0053_auto_20161104_1314'),
        ('staff', '0003_auto_20170209_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPageLibraryUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('library_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_staffpagelibraryunits_related', to='units.UnitPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='staffpage',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='staffpage',
            name='chicago_id',
            field=models.CharField(blank=True, help_text='Campus-wide unique identifier', max_length=9),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='employee_type',
            field=models.IntegerField(choices=[(1, 'Clerical'), (2, 'Exempt'), (3, 'IT'), (4, 'Librarian')], default=1, help_text='Clerical, exempt, IT or Librarian.'),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='faculty_exchange',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Please enter the phone number using the format 773-123-4567', regex='^[0-9]{3}-[0-9]{3}-[0-9]{4}$')]),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='position_status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Vacant'), (3, 'Eliminated')], default=1, help_text='Help remember and reassign editing responsibilities when staff change positions.'),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='position_title',
            field=models.CharField(blank=True, help_text='Position title.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='supervises_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='supervisor_override',
            field=models.ForeignKey(blank=True, help_text="If supervisor cannot be determined by the staff person's unit, specify supervisor here.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_override_for', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='cnetid',
            field=models.CharField(help_text='Campus-wide unique identifier which links this record to the campus directory.', max_length=255),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='display_name',
            field=models.CharField(blank=True, help_text="Version of this staff person's name to display.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name, for sorting.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name, for sorting.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Middle name, for sorting.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='official_name',
            field=models.CharField(blank=True, help_text="Official version of this staff person's name.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffpagelibraryunits',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_page_units', to='staff.StaffPage'),
        ),
    ]
