# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20170705_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPageEmailAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='staffpage',
            name='email',
        ),
        migrations.AddField(
            model_name='staffpageemailaddresses',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_page_email', to='staff.StaffPage'),
        ),
    ]
