# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 18:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20170705_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPagePhoneFacultyExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Please enter the phone number using the format 773-123-4567', regex='^[0-9]{3}-[0-9]{3}-[0-9]{4}$')])),
                ('faculty_exchange', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='staffpage',
            name='faculty_exchange',
        ),
        migrations.RemoveField(
            model_name='staffpage',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='staffpagephonefacultyexchange',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_page_phone_faculty_exchange', to='staff.StaffPage'),
        ),
    ]
