# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20170705_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffpagepagevcards',
            name='page',
        ),
        migrations.RemoveField(
            model_name='staffpagepagevcards',
            name='vcard_ptr',
        ),
        migrations.RemoveField(
            model_name='vcard',
            name='unit',
        ),
        migrations.DeleteModel(
            name='StaffPagePageVCards',
        ),
        migrations.DeleteModel(
            name='VCard',
        ),
    ]
