# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 19:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20170913_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpage',
            name='orcid',
            field=models.CharField(blank=True, help_text='See https://orcid.org for more information.', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter ORCIDs as a 16 digit number with hyphens, e.g. 1111-2222-3333-4444', regex='^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}$')]),
        ),
    ]
