# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20170913_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpage',
            name='is_public_persona',
            field=models.BooleanField(default=False, help_text='(display changes not yet implemented)'),
        ),
    ]
