# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20170913_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpage',
            name='libguide_url',
            field=models.URLField(blank=True, help_text='Your profile page on guides.lib.uchicago.edu.', max_length=255, null=True),
        ),
    ]
