# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20170913_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpage',
            name='cv',
            field=models.ForeignKey(blank=True, help_text='Your CV or resume.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
