# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_auto_20170926_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpagelibraryunits',
            name='library_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_staffpagelibraryunits_related', to='units.UnitPage'),
        ),
    ]
