# Generated by Django 2.0.12 on 2019-05-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_auto_20171121_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffpage',
            name='position_status',
        ),
        migrations.AddField(
            model_name='staffpage',
            name='position_eliminated',
            field=models.BooleanField(default=False, help_text='Position will not be refilled.'),
        ),
    ]
