# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_auto_20160301_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffindexpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_staffindexpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='staffindexpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_staffindexpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_staffpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_staffpage_maintainer', to='staff.StaffPage'),
        ),
    ]
