# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 19:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_auto_20160328_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpage',
            name='orcid',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter ORCIDs as a 16 digit number with hyphens, e.g. 1111-2222-3333-4444', regex='^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]$')]),
        ),
    ]
