# Generated by Django 3.0.6 on 2020-08-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_auto_20200807_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpage',
            name='pronouns',
            field=models.CharField(blank=True, help_text='Your pronouns, example: (they/them/theirs)', max_length=255, null=True),
        ),
    ]
