# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailsearch.index


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_auto_20160502_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            bases=(models.Model, wagtail.wagtailsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='StaffPageExpertisePlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staff.Expertise')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_placements', to='staff.StaffPage')),
            ],
            options={
                'verbose_name': 'Expertise Placement',
                'verbose_name_plural': 'Expertise Placements',
            },
        ),
    ]
