# Generated by Django 5.2.6 on 2025-10-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0029_alter_staffindexpage_editor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffpage",
            options={
                "ordering": ["last_name", "first_name"],
                "permissions": [
                    (
                        "change_staff_hr_info",
                        "Can edit Human Resources Info for staff pages",
                    )
                ],
            },
        ),
    ]
