# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0036_auto_20160913_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffpage',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='staffpage',
            name='page_maintainer',
        ),
    ]
