# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0041_auto_20161014_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffpage',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
