# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('intranethome', '0001_initial'), ('intranethome', '0003_auto_20151202_1651'), ('intranethome', '0004_auto_20151203_1806'), ('intranethome', '0005_auto_20151209_2251'), ('intranethome', '0006_auto_20160328_1905'), ('intranethome', '0007_remove_intranethomepage_sort_order'), ('intranethome', '0008_auto_20161103_1604'), ('intranethome', '0009_auto_20161104_1314')]

    initial = True

    dependencies = [
        ('wagtailcore', '0019_verbose_names_cleanup'),
        ('staff', '0000_manual_pre_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntranetHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intranethome_intranethomepage_editor', to='staff.StaffPage')),
                ('last_reviewed', models.DateField(blank=True, null=True, verbose_name='Last Reviewed')),
                ('page_maintainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intranethome_intranethomepage_maintainer', to='staff.StaffPage')),
                ('show_sidebar', models.BooleanField(default=False)),
                ('start_sidebar_from_here', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
