# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirbrowse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirbrowsepage',
            name='dir_browse_script_url',
            field=models.CharField(max_length=255),
        ),
    ]
