# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dirbrowse', '0008_remove_dirbrowsepage_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirbrowsepage',
            name='quicklinks',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='dirbrowsepage',
            name='quicklinks_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dirbrowsepage',
            name='view_more_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dirbrowsepage',
            name='view_more_link_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
