# Generated by Django 2.0.12 on 2019-09-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirbrowse', '0009_remove_dirbrowsepage_news_feed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirbrowsepage',
            name='news_feed_source',
            field=models.CharField(blank=True, choices=[('', '--------'), ('library_kiosk', 'Library'), ('law_kiosk', 'Law'), ('crerar_kiosk', 'Crerar'), ('scrc_kiosk', 'SCRC')], default='', max_length=50),
        ),
    ]
