# Generated by Django 2.0.12 on 2187-02-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirbrowse', '0010_dirbrowsepage_news_feed_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirbrowsepage',
            name='news_feed_source',
            field=models.CharField(blank=True, choices=[('', '--------'), ('library_kiosk', 'Library'), ('law_kiosk', 'Law'), ('sciences_kiosk', 'Sciences'), ('scrc_kiosk', 'SCRC')], default='', max_length=50),
        ),
    ]
