# Generated by Django 5.0.10 on 2025-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatbotpage",
            name="intro",
        ),
    ]
