# Generated by Django 5.0.10 on 2025-05-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_remove_chatbotpage_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
    ]
