# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20170926_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembers',
            name='group_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='parent',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='group.GroupPage'),
        ),
    ]
