# Generated by Django 2.0.3 on 2018-03-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20171108_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembers',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='group.GroupMemberRole'),
        ),
    ]
