# Generated by Django 2.2.10 on 2020-04-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_auto_20200327_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmeetingminutespagetable',
            name='link_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
