# Generated by Django 5.2.8 on 2025-12-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0019_alter_grouppage_body_alter_grouppage_intro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouppage",
            name="is_active",
        ),
    ]
