# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0081_auto_20160609_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupindexpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='groupmeetingminutesindexpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='groupmeetingminutespage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='grouppage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='groupreportsindexpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='groupreportspage',
            name='sort_order',
        ),
    ]
