# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20170531_1545'),
        ('units', '0001_initial_squashed_0053_auto_20161104_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpage',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head_of', to='staff.StaffPage'),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='department_head_is_interim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='display_in_campus_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='faculty_exchange',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='internal_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='is_a_division',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='phone_number_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='public_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='public_url_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='unitpage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
