# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20170531_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpage',
            name='building',
            field=models.IntegerField(choices=[(1, 'Crerar Library'), (2, "D'Angelo Law Library"), (3, 'Eckhart Library'), (4, 'Mansueto Library'), (5, 'Regenstein Library'), (6, 'Special Collections Research Center'), (7, 'SSA Library')], default=5, help_text='The physical building where this unit is located.'),
        ),
    ]
