# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20170714_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitpage',
            name='directory_unit',
        ),
    ]
