# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_auto_20170721_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitpage',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='unitpage',
            name='phone_number_label',
        ),
    ]
