# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_auto_20170908_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpage',
            name='public_web_page',
            field=models.ForeignKey(blank=True, help_text='The name of this department will hyperlink to this page in                    the departmental directory on the library website.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
