# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_auto_20170911_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpage',
            name='display_in_campus_directory',
            field=models.BooleanField(default=True, help_text='This unit will appear in reports showing where Wagtail                    UnitPages differ from campus directory units.'),
        ),
    ]
