# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_auto_20170911_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitpage',
            old_name='display_in_directory',
            new_name='display_in_library_directory',
        ),
    ]
