# Generated by Django 2.0.3 on 2018-10-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_auto_20170913_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpage',
            name='building',
            field=models.IntegerField(choices=[(1, 'The John Crerar Library'), (2, "The D'Angelo Law Library"), (3, 'Eckhart Library'), (4, 'The Joe and Rika Mansueto Library'), (5, 'The Joseph Regenstein Library'), (6, 'Special Collections Research Center'), (7, 'Social Service Administration Library')], default=5, help_text='The physical building where this unit is located.'),
        ),
    ]
