# Generated by Django 3.0.7 on 2021-06-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0012_auto_20181019_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpage',
            name='building',
            field=models.IntegerField(choices=[(1, 'The John Crerar Library'), (2, "The D'Angelo Law Library"), (3, 'Eckhart Library'), (4, 'The Joe and Rika Mansueto Library'), (5, 'The Joseph Regenstein Library'), (6, 'The Hanna Holborn Gray Special Collections Research Center'), (7, 'The Social Service Administration Library')], default=5, help_text='The physical building where this unit is located.'),
        ),
    ]
