# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0029_auto_20160107_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpage',
            name='display_in_directory',
            field=models.BooleanField(default=True),
        ),
    ]
