# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0042_auto_20160205_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPageEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('email_label', models.CharField(blank=True, max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='unitpage',
            name='email',
        ),
        migrations.AlterField(
            model_name='unitpagephonenumbers',
            name='phone_label',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='unitpageemail',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='units.UnitPage'),
        ),
    ]
