# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 17:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0004_capitalizeverbose'),
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('units', '0044_auto_20160307_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitpageemail',
            name='page',
        ),
        migrations.RemoveField(
            model_name='unitpagephonenumbers',
            name='page',
        ),
        migrations.RemoveField(
            model_name='unitpagereports',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='unitpagereports',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='unitpagereports',
            name='page',
        ),
        migrations.RemoveField(
            model_name='unitpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='unitpage',
            name='contact_url',
        ),
        migrations.AddField(
            model_name='unitpage',
            name='contact_point_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='display_in_dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='email_label',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='link_external',
            field=models.URLField(blank=True, verbose_name='External link'),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='phone_label',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='unitpage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Please enter the phone number using the format 773-123-4567', regex='^[0-9]{3}-[0-9]{3}-[0-9]{4}$')]),
        ),
        migrations.DeleteModel(
            name='UnitPageEmail',
        ),
        migrations.DeleteModel(
            name='UnitPagePhoneNumbers',
        ),
        migrations.DeleteModel(
            name='UnitPageReports',
        ),
    ]
