# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0045_auto_20160309_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpage',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
