# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0047_unitpage_link_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitpage',
            options={'ordering': ['title']},
        ),
    ]
