# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0048_auto_20160314_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpage',
            name='alphabetical_directory_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
