"""
Django settings for library_website project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sitemaps',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bleach',
    'taggit',
    'compressor',
    'modelcluster',
    'wagtailcache',
    'wagtail.core',
    'wagtail.admin',
    'wagtail.search',
    'wagtail.images',
    'wagtail.documents',
    'wagtailmedia',
    'wagtail.snippets',
    'wagtail.users',
    'wagtail.sites',
    'wagtail.embeds',
    'wagtail.contrib.redirects',
    'wagtail.contrib.forms',
    'wagtail.contrib.table_block',
    'wagtail.contrib.routable_page',
    'wagtail.contrib.search_promotions',
    'wagtail.contrib.sitemaps',
    'wagtail.contrib.settings',
    'wagtail.contrib.styleguide',
    'wagtail.api.v2',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'alerts',
    'ask_a_librarian',
    'base',
    'conferences',
    'dirbrowse',
    'events',
    'findingaids',
    'group',
    'home',
    'icon_list_boxes',
    'intranetforms',
    'intranethome',
    'intranettocs',
    'intranetunits',
    'lib_collections',
    'lib_news',
    'library_website',
    'macros',
    'news',
    'public',
    'projects',
    'redirects',
    'results',
    'reusable_content',
    'search',
    'searchable_content',
    'shibboleth',
    'site_settings',
    'staff',
    'subjects',
    'units',
    'static_precompiler',
    'workflowautomator.apps.WorkflowautomatorConfig',
    'webpack_loader',
]

MIDDLEWARE = [
    'wagtailcache.cache.UpdateCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    # Required for shibboleth
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'shibboleth.middleware.ShibbolethRemoteUserMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'wagtailcache.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'library_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shibboleth.context_processors.login_link',
                'shibboleth.context_processors.logout_link',
                'wagtail.contrib.settings.context_processors.settings',
            ],
            'loaders': [
                (
                    'django.template.loaders.cached.Loader', [
                        'django.template.loaders.filesystem.Loader',
                        'django.template.loaders.app_directories.Loader',
                    ]
                ),
            ],
        },
    },
]

WSGI_APPLICATION = 'library_website.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# Don't put database information here!!!

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = False

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
    'static_precompiler.finders.StaticPrecompilerFinder',
)

STATICFILES_DIRS = (os.path.join(PROJECT_DIR, 'static'),)

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

WAGTAILEMBEDS_RESPONSIVE_HTML = True

# Phone number format
PHONE_FORMAT = '^[0-9]{3}-[0-9]{3}-[0-9]{4}$'
PHONE_ERROR_MSG = 'Please enter the phone number using the format 773-123-4567'

# Postal code format
POSTAL_CODE_FORMAT = '^[0-9]{5}$'
POSTAL_CODE_ERROR_MSG = 'Please enter the postal code as a five digit number, e.g. 60637'

# ORCID
ORCID_FORMAT = '^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}$'
ORCID_ERROR_MSG = 'Please enter ORCIDs as a 16 digit number with hyphens, e.g. 1111-2222-3333-4444'

# django-compressor settings
COMPRESS_PRECOMPILERS = (('text/x-scss', 'django_libsass.SassCompiler'),)

# django-static-precompilers
STATIC_PRECOMPILER_COMPILERS = (
    (
        'static_precompiler.compilers.libsass.SCSS', {
            'load_paths': [os.path.join(BASE_DIR, 'base/static/base/css')],
            'output_style': 'compressed'
        }
    ),
)

# Wagtail settings
WAGTAIL_SITE_NAME = "library_website"

WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.search.backends.elasticsearch5',
        'URLS': ['http://localhost:9200'],
        'INDEX': 'wagtail',
        'TIMEOUT': 5,
        'INDEX_SETTINGS': {
            'settings': {
                'index': {
                    'analysis': {
                        'analyzer': {
                            'default': {
                                'type': 'english'
                            },
                        },
                    }
                }
            }
        },
    }
}

# Settings for cross origin requests
# Documentation and settings:
# https://github.com/OttoYiu/django-cors-headers
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = (
    'https://catalog.lib.uchicago.edu',
    'https://catalogtest.lib.uchicago.edu',
    'https://dldc1.lib.uchicago.edu',
    'https://dldc2.lib.uchicago.edu',
    'https://dldc3.lib.uchicago.edu',
    'https://forms2.lib.uchicago.edu',
    'http://guides.lib.uchicago.edu',
    'https://guides.lib.uchicago.edu',
    'https://rooms.lib.uchicago.edu',
    'https://sfx.lib.uchicago.edu',
    'https://sfx.lib.uchicago.edu:3103',
)
CORS_ALLOW_METHODS = (
    'GET',
    # 'POST',
    # 'PUT',
    # 'PATCH',
    # 'DELETE',
    # 'OPTIONS'
)

# Lock down specific nodes to wagtail groups. Sections are locked down
# by page ID. In order to see any page, a user must belong to all groups
# set in all page ancestors. This works as a blacklist.
# PERMISSIONS_MAPPING = {6: ['Library'], 319: ['Foo', 'Bar']}
PERMISSIONS_MAPPING = {6: ['Library']}

# Where to send users that aren't members of the necessary groups to
# view a page.
NO_PERMISSIONS_REDIRECT_URL = 'https://www.lib.uchicago.edu/no-permission/'

# Settings for RESTful API and frontend cache invalidation
WAGTAILAPI_SEARCH_ENABLED = True
WAGTAILAPI_MAX_RESULTS = 60

# Institutional ID for libcal
LIBCAL_IID = 482

# Fallback unit for pages that don't have one (Library - Regenstein Library)
DEFAULT_UNIT = 2455

# The unit for pages that are assigned to The University of Chicago Libraries.
# In other words generic pages that are not branch library specific use this number.
ROOT_UNIT = 2455

PUBLIC_HOMEPAGE = 3378

# Restricted directory locked down to campus by shib
RESTRICTED = 3831

# String templates for hours and address display in the header and footer
HOURS_TEMPLATE = '%s &nbsp; %s'
ADDRESS_TEMPLATE = '%s, %s, %s %s'

# Location and hours page
HOURS_PAGE = 4084

# Library news categories
NEWS_CATEGORIES = set(
    [
        'Resources', 'Research', 'Teaching', 'Events', 'Exhibits', 'People',
        'Hours & Access', 'Spaces', 'Spotlight', 'From the Director'
    ]
)

# SCRC special situations
SCRC_MAIN_UNIT = 2456
SCRC_ASK_PAGE = 4127

# UChicago Library Pages
REGENSTEIN_HOMEPAGE = 1797
SSA_HOMEPAGE = 1758
MANSUETO_HOMEPAGE = 1753
CRERAR_HOMEPAGE = 1752
ECKHART_HOMEPAGE = 1755
DANGELO_HOMEPAGE = 1754
SCRC_HOMEPAGE = 1756
DISSERTATION_HOMEPAGE = 1672

# Loop Email Notification header and footer
LOOP_EMAIL_NOTIFICATION_HEADER = "Here is a round-up of some interesting Loop news stories that you may have missed."
LOOP_EMAIL_NOTIFICATION_FOOTER = "As always, contact <a href='mailto:intranet@lib.uchicago.edu'>intranet@lib.uchicago.edu</a> with any questions or feedback regarding Loop."

# Site IDs
PUBLIC_SITE = 3

# Quick numbers for directory
# Links should be integers (page ID)
# If a link is present, the phone number
# will not be used
QUICK_NUMS = {
    'the-university-of-chicago-library': [
        {
            'label': 'Main Telephone',
            'number': '773-702-8740',
            'link': None
        }, {
            'label': 'Privileges',
            'number': '773-702-8782',
            'link': None
        }, {
            'label': 'General Reference',
            'number': '773-702-4685',
            'link': None
        }
    ],
    'the-joseph-regenstein-library': [
        {
            'label': 'Main Telephone',
            'number': '773-702-8740',
            'link': None
        }, {
            'label': 'Privileges',
            'number': '773-702-8782',
            'link': None
        }, {
            'label': 'General Reference',
            'number': '773-702-4685',
            'link': None
        }
    ],
    'the-john-crerar-library': [
        {
            'label': 'Crerar Circulation',
            'number': '773-702-7409',
            'link': None
        }, {
            'label': 'Crerar Reference',
            'number': '773-702-7715',
            'link': None
        }
    ],
    'the-dangelo-law-library': [
        {
            'label': 'D\'Angelo Law Main Telephone',
            'number': '773-702-9615',
            'link': None
        }, {
            'label': 'D\'Angelo Law Circulation',
            'number': '773-702-0213',
            'link': None
        }, {
            'label': 'D\'Angelo Law Reference',
            'number': '773-702-9631',
            'link': None
        }
    ],
    'eckhart-library':
    [{
        'label': 'Eckhart Library',
        'number': '773-702-8778',
        'link': None
    }],
    'the-joe-and-rika-mansueto-library': [
        {
            'label': 'Mansueto Circulation Desk',
            'number': '773-702-0901',
            'link': None
        }
    ],
    'the-hanna-holborn-gray-special-collections-research-center': [
        {
            'label': 'SCRC Front Desk',
            'number': '773-702-8705',
            'link': None
        }, {
            'label': 'SCRC Contact Form',
            'number': '',
            'link': SCRC_ASK_PAGE
        }
    ],
    'the-social-work-library':
    [{
        'label': 'SSA Library',
        'number': '773-702-1199',
        'link': None
    }],
}

# This setting is used in units/models.py and staff/templatetags/staff_tags.py.
# The code should be updated to use LocationPage.objects.live().filter(is_building=True) instead
BUILDINGS = (
    (1, 'The John Crerar Library'),
    (2, 'The D\'Angelo Law Library'),
    (3, 'Eckhart Library'),
    (4, 'The Joe and Rika Mansueto Library'),
    (5, 'The Joseph Regenstein Library'),
    (6, 'The Hanna Holborn Gray Special Collections Research Center'),
    (7, 'The Social Work Library')
)

# Location pages
SCRC_BUILDING_ID = 2971
CRERAR_BUILDING_ID = 2713

# Web Exhibit footers
CRERAR_EXHIBIT_FOOTER_IMG = 1130
SCRC_EXHIBIT_FOOTER_IMG = 1129

WAGTAIL_CACHE_BACKEND = 'pagecache'

# Redis cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://localhost:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    },
    'pagecache': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache'),
        'KEY_PREFIX': 'wagtailcache',
        'TIMEOUT': 21600,
    }
}

# Base url for the LibChat status API
LIBCHAT_STATUS_URL = 'https://uchicago.libanswers.com/1.0/chat/widgets/status/'

# Map LibraryH3lp chat widget names to LibChat widget IDs
# Implemented to avoid changing function signatures and
# page models when we migrated to LibChat. Preferable
# since it documents this for us.
LIBCHAT_IDS = {
    'uofc-ask': '9650',
    'dissertation-office': '11495',
    'law': '11496',
    'crerar': '9650',
    'ssa': '9650'
}

# API configuration
WAGTAILAPI_LIMIT_MAX = None

# OwnCloud settings
OWNCLOUD_USERNAME = 'ldr_oc_admin'
OWNCLOUD_WEB_SERVICE = 'https://s3.lib.uchicago.edu/owncloud'

# Uploaded files and documents should have group read/write permissions
# and world read permissions.
FILE_UPLOAD_PERMISSIONS = 0o664

# Config for frontent dependencies
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
    }
}

# Public news site
NEWS_FEED_DEFAULT_VISIBLE = 9
NEWS_FEED_INCREMENT_BY = 18
LIBRA_ID = 1664
STATIC_NEWS_FEED = os.path.join(
    STATIC_ROOT, 'lib_news', 'files', 'lib-news.json'
)
DRF_NEWS_FEED = '/api/v2/pages/?format=json&treat_as_webpage=false&order=-published_at&type=lib_news.LibNewsPage&fields=*&limit=1000'

# Cache time for news site categories is 3 hours
NEWS_CACHE_TTL = 60 * 180

# University Events Feed
UC_EVENTS_FEED = 'https://events.uchicago.edu/widgets/rss.php?key=47866f880d62a4f4517a44381f4a990d&id=48'

# Tiny Tiny RSS Feed
TTRSS_FEED = 'https://wicket.lib.uchicago.edu/tt-rss/public.php?op=rss&id=-3&key=8idjnk57e2a0063541d'

# Authorization key for LibCal admin interface
LIBCAL_TOKEN_ENDPOINT = ''
LIBCAL_ENDPOINT = ''
LIBCAL_CREDENTIALS = {
    'grant_type': '',
    'client_id': '',
    'client_secret': '',
}

# CGIMail Forms
CGI_MAIL_SERVICE = '/cgi-bin/cgimail/cgimail'
ITEM_SERVLET = 'https://forms2.lib.uchicago.edu/lib/searchform/itemServlet.php?format=json'
SPRINGSHARE_PRIVACY_POLICY = 'https://springshare.com/privacy.html'

# Override settings in test
# -------------------------------
# THESE ONLY APPLY TO UNIT TESTS!
# -------------------------------

if 'test' in sys.argv:
    HOURS_PAGE = 1

# DOI resolution service

IDRESOLVE_URL = "https://www.lib.uchicago.edu/cgi-bin/idresolve"

MARKLOGIC_LDR_PORT = 8008

MARKLOGIC_LDR_BASE = "http://marklogic.lib.uchicago.edu"

MARKLOGIC_LDR_ROUTE = "/v1/graphs"

MARKLOGIC_LDR_URL = "%s:%i%s" % (MARKLOGIC_LDR_BASE,
                                 MARKLOGIC_LDR_PORT,
                                 MARKLOGIC_LDR_ROUTE
                                 )

MARKLOGIC_FINDINGAIDS_PORT = 8011

# "http://marklogic.lib.uchicago.edu:8011/admin/gimme.xqy?collection=institution%2FUniversity%20of%20Chicago")

EBOOKS_SEARCH = 'https://catalog.lib.uchicago.edu/vufind/Search/Results?filter%5B%5D=format%3A%22Book%22&filter%5B%5D=format%3A%22E-Resource%22&type=AllFields&lookfor='

SPARQL_ROOT = "https://repository.lib.uchicago.edu/digital_collections"

LANGUAGE_ABBREVS = {'en': 'English'}

# toggle this comment to go between dev and production
IIIF_PREFIX = "https://iiif-collection.lib.uchicago.edu"
# IIIF_PREFIX = "https://iiif-collection-dev.lib.uchicago.edu"

# toggle this comment with the other to switch from dev to production
# IIIF_VIEWER_PREFIX = "https://liblet.lib.uchicago.edu/viewer?manifest="
IIIF_VIEWER_PREFIX = "https://www.lib.uchicago.edu/viewer?manifest="

WAGTAIL_PREFIX = "/collex/collections"

# toggle these root URLs for dev/production
# CITATION_ROOT = "http://sequent.lib.uchicago.edu:9000"
CITATION_ROOT = "http://www.lib.uchicago.edu/cgi-bin/citation"

TURTLE_ROOT = "https://ark.lib.uchicago.edu/ark:61001/"

# CSL file paths
APA_PATH = BASE_DIR + "/lib_collections/csl/apa.csl"

MLA_PATH = BASE_DIR + "/lib_collections/csl/modern-language-association.csl"

CHICAGO_PATH = BASE_DIR + "/lib_collections/csl/chicago-author-date.csl"


# how many characters to truncate breadcrumb trail text at, in the
# digital collecitons app
COLLECTION_OBJECT_TRUNCATE = 25
