# Generated by Django 2.0.8 on 2018-11-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchable_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchablecontent',
            name='subject',
        ),
        migrations.AddField(
            model_name='searchablecontent',
            name='content',
            field=models.CharField(default='', max_length=255, verbose_name='subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchablecontent',
            name='datestamp',
            field=models.CharField(max_length=255, verbose_name='datestamp'),
        ),
        migrations.AlterField(
            model_name='searchablecontent',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='searchablecontent',
            name='tag',
            field=models.CharField(max_length=255, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='searchablecontent',
            name='url',
            field=models.CharField(max_length=255, verbose_name='url'),
        ),
    ]
