# Generated by Django 2.0.8 on 2018-11-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchable_content', '0002_auto_20181130_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchablecontent',
            name='content',
            field=models.TextField(verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='searchablecontent',
            name='datestamp',
            field=models.DateField(verbose_name='datestamp'),
        ),
        migrations.AlterField(
            model_name='searchablecontent',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='searchablecontent',
            name='url',
            field=models.URLField(verbose_name='url'),
        ),
    ]
