# Generated by Django 2.0.8 on 2018-12-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchable_content', '0003_auto_20181130_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchablecontent',
            name='identifier',
            field=models.CharField(default=1, help_text='A unique identifier, like a primary key or URL, from the       producer of this data. This identifier should be unique to that       producer, but it does not necessarily have to be unique across this       entire database table.', max_length=255, verbose_name='identifier'),
            preserve_default=False,
        ),
    ]
