# Generated by Django 2.0.8 on 2018-12-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchable_content', '0005_auto_20181203_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibGuidesSearchableContent',
            fields=[
                ('searchablecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='searchable_content.SearchableContent')),
                ('tags', models.TextField(verbose_name='tags')),
                ('subjects', models.TextField(verbose_name='subjects')),
            ],
            bases=('searchable_content.searchablecontent',),
        ),
        migrations.RemoveField(
            model_name='searchablecontent',
            name='tag',
        ),
        migrations.AlterField(
            model_name='searchablecontent',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
    ]
