# Generated by Django 2.0.12 on 2019-06-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchable_content', '0007_libguidesassetssearchablecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchablecontent',
            name='url',
            field=models.URLField(max_length=300, verbose_name='url'),
        ),
    ]
