# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    replaces = [('intranettocs', '0001_initial'), ('intranettocs', '0002_auto_20160127_1933'), ('intranettocs', '0003_auto_20160328_1905'), ('intranettocs', '0004_remove_tocpage_sort_order'), ('intranettocs', '0005_auto_20161103_1604'), ('intranettocs', '0006_auto_20161104_1314')]

    initial = True

    dependencies = [
        ('staff', '0000_manual_pre_initial'),
        ('wagtailcore', '0020_add_index_on_page_first_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOCPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('start_sidebar_from_here', models.BooleanField(default=False)),
                ('show_sidebar', models.BooleanField(default=False)),
                ('last_reviewed', models.DateField(blank=True, null=True, verbose_name='Last Reviewed')),
                ('body', wagtail.wagtailcore.fields.StreamField((('list_block', wagtail.wagtailcore.blocks.StructBlock((('icon', wagtail.wagtailcore.blocks.CharBlock(help_text='Add a Font Awesome icon name here')), ('heading', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.RichTextBlock())))), ('automatic_directory_list_block', wagtail.wagtailcore.blocks.StructBlock((('icon', wagtail.wagtailcore.blocks.CharBlock(help_text='Add a Font Awesome icon name here')), ('starting_page', wagtail.wagtailcore.blocks.PageChooserBlock()))))))),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intranettocs_tocpage_editor', to='staff.StaffPage')),
                ('page_maintainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intranettocs_tocpage_maintainer', to='staff.StaffPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
