# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 19:33
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intranettocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocpage',
            name='body',
            field=wagtail.fields.StreamField((('list_block', wagtail.blocks.StructBlock((('icon', wagtail.blocks.CharBlock(help_text='Add a Font Awesome icon name here')), ('heading', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock())))), ('automatic_directory_list_block', wagtail.blocks.StructBlock((('icon', wagtail.blocks.CharBlock(help_text='Add a Font Awesome icon name here')), ('starting_page', wagtail.blocks.PageChooserBlock())))))),
        ),
    ]
