# Generated by Django 3.2.15 on 2022-09-20 16:54

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intranettocs', '0001_squashed_0006_auto_20161104_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocpage',
            name='body',
            field=wagtail.fields.StreamField([('list_block', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(help_text='Add a Font Awesome icon name here')), ('heading', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock())])), ('automatic_directory_list_block', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(help_text='Add a Font Awesome icon name here')), ('starting_page', wagtail.blocks.PageChooserBlock())]))], use_json_field=True),
        ),
    ]
