# Generated by Django 5.2.8 on 2025-12-11 22:43

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0032_alter_staffpage_bio"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="CGIMailFormEditorPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("start_sidebar_from_here", models.BooleanField(default=False)),
                ("show_sidebar", models.BooleanField(default=False)),
                (
                    "last_reviewed",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Reviewed"
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Introductory text displayed at the top of the tool",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default='You are an expert at generating CGIMail form JSON configurations for the University of Chicago Library website.\n\nYour task is to generate valid JSON that follows the CGIMailFormSchema exactly. Output ONLY valid JSON with no explanations or markdown.\n\nKey requirements:\n1. The first section must always be hidden with a \'rcpt\' field containing the recipient surrogate.\n   These should never be email addresses. Surrogates are just text. Do not convert them into email\n   addresses.\n2. Use appropriate field types: text, email, textarea, select, checkbox, radio, hidden.\n3. Group related fields using fieldset (with legend) or group (side-by-side).\n4. Add helpful placeholder text and help text where appropriate.\n5. Mark required fields with required: true.\n6. Select boxes: Options for these are not lists of strings. They are lists of objects that have\n   value and text attributes. Always give these a default "unselected" state.\n7. Conditional fields: Use enabledWhen to show a field only when another field has a specific value.\n   - enabledWhen.field must match the controlling field\'s name attribute (not id)\n   - enabledWhen.value must exactly match one of the controlling field\'s option values\n   Example: To show "Select your year" only for undergraduates:\n   First field:  {"name": "UChicago_Affiliation", "options": [{"value": "", "text": "-- Select --", "disabled": true, "selected": true}, {"value": "Undergraduate student", ...}]}\n   Second field: {"name": "Year", "enabledWhen": {"field": "UChicago_Affiliation", "value": "Undergraduate student"}}',
                        help_text="System prompt sent to the AI model",
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        choices=[
                            ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                            ("gpt-4o", "GPT-4o"),
                            ("gpt-4-turbo", "GPT-4 Turbo"),
                            ("gpt-5.1", "GPT-5.1"),
                            ("o3", "o3"),
                            ("chatgpt-4o-latest", "ChatGPT-4o Latest"),
                        ],
                        default="chatgpt-4o-latest",
                        help_text="OpenAI model to use for generation",
                        max_length=50,
                    ),
                ),
                (
                    "template_description",
                    models.TextField(
                        blank=True,
                        default="Create an appointment request form with:\n- Name (required)\n- Email address (required)\n- UChicago affiliation dropdown (Undergraduate student, Graduate student, Faculty or instructor, Staff, Alumni, Visitor / Not UChicago)\n- If undergraduate, year dropdown (1st Year, 2nd Year, 3rd Year, Senior)\n- Major, department, or program text field\n- Research question summary (required, large text area)\n- Is this for a UChicago course? dropdown (Yes, No)\n- If yes, course name and number text field\n- Research done so far (large text area)\n- Accommodation notes (large text area)",
                        help_text="Pre-populated template description (click 'Load Example' to use)",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_editor",
                        to="staff.staffpage",
                    ),
                ),
                (
                    "page_maintainer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_maintainer",
                        to="staff.staffpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "CGIMail Form Editor Page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="DocumentationSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="External documentation URL (can be any website)",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Context for AI (e.g., 'Developer documentation', 'CGIMail reference')",
                        max_length=255,
                    ),
                ),
                (
                    "internal_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Internal Wagtail page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentation_sources",
                        to="cgimail_editor.cgimailformeditorpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documentation Source",
                "verbose_name_plural": "Documentation Sources for AI context",
            },
        ),
    ]
