# Generated by Django 5.2.12 on 2026-07-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cgimail_editor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cgimailformeditorpage",
            name="ai_model",
            field=models.CharField(
                choices=[
                    ("gpt-5.5", "GPT-5.5"),
                    ("gpt-5.4", "GPT-5.4"),
                    ("gpt-5.4-mini", "GPT-5.4 Mini"),
                    ("gpt-5.3-chat-latest", "GPT-5.3 Chat Latest"),
                ],
                default="gpt-5.5",
                help_text="OpenAI model to use for generation",
                max_length=50,
            ),
        ),
    ]
