# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 17:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intranetforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intranetformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='intranetforms.IntranetFormPage'),
        ),
    ]
