# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_auto_20160301_1838'),
        ('intranetforms', '0002_auto_20160308_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='intranetformpage',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intranetforms_intranetformpage_editor', to='staff.StaffPage'),
        ),
        migrations.AddField(
            model_name='intranetformpage',
            name='last_reviewed',
            field=models.DateField(blank=True, null=True, verbose_name='Last Reviewed'),
        ),
        migrations.AddField(
            model_name='intranetformpage',
            name='page_maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intranetforms_intranetformpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AddField(
            model_name='intranetformpage',
            name='show_sidebar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intranetformpage',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='intranetformpage',
            name='start_sidebar_from_here',
            field=models.BooleanField(default=False),
        ),
    ]
