# Generated by Django 3.1.12 on 2021-06-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetforms', '0003_auto_20180327_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='intranetformfield',
            name='clean_name',
            field=models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name'),
        ),
    ]
