# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    replaces = [('findingaids', '0001_initial'), ('findingaids', '0002_remove_findingaidspage_sort_order'), ('findingaids', '0003_auto_20160616_1727'), ('findingaids', '0004_findingaidspage_display_hours_in_right_sidebar'), ('findingaids', '0005_auto_20160623_1449'), ('findingaids', '0006_findingaidspage_events_feed_url'), ('findingaids', '0007_auto_20160624_1847'), ('findingaids', '0008_findingaidspage_news_feed_url'), ('findingaids', '0009_findingaidspage_active_tag'), ('findingaids', '0010_auto_20160629_2118'), ('findingaids', '0011_findingaidspage_rich_text_external_link'), ('findingaids', '0012_findingaidspage_change_to_callout'), ('findingaids', '0013_remove_findingaidspage_active_tag'), ('findingaids', '0014_auto_20160702_1751'), ('findingaids', '0015_auto_20160702_1754'), ('findingaids', '0016_auto_20160708_1033'), ('findingaids', '0017_findingaidspage_banner_subtitle'), ('findingaids', '0018_findingaidspage_banner_feature'), ('findingaids', '0019_auto_20161103_1604'), ('findingaids', '0020_auto_20161104_1314')]

    initial = True

    dependencies = [
        ('units', '0000_manual_pre_initial'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('staff', '0000_manual_pre_initial'),
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingAidsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('start_sidebar_from_here', models.BooleanField(default=False)),
                ('show_sidebar', models.BooleanField(default=False)),
                ('last_reviewed', models.DateField(blank=True, null=True, verbose_name='Last Reviewed')),
                ('content_specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findingaids_findingaidspage_content_specialist', to='staff.StaffPage')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findingaids_findingaidspage_editor', to='staff.StaffPage')),
                ('page_maintainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findingaids_findingaidspage_maintainer', to='staff.StaffPage')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findingaids_findingaidspage_related', to='units.UnitPage')),
                ('quicklinks', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('quicklinks_title', models.CharField(blank=True, max_length=100)),
                ('view_more_link', models.URLField(blank=True, default='', max_length=255)),
                ('view_more_link_label', models.CharField(blank=True, max_length=100)),
                ('display_hours_in_right_sidebar', models.BooleanField(default=False)),
                ('display_hierarchical_listing', models.BooleanField(default=False)),
                ('enable_index', models.BooleanField(default=False)),
                ('events_feed_url', models.URLField(blank=True, help_text='Link to a Tiny Tiny RSS Feed')),
                ('news_feed_url', models.URLField(blank=True, help_text='Link to a wordpress feed from the Library News Site')),
                ('rich_text', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Should be a bulleted list or combination of h3 elements and bulleted lists')),
                ('rich_text_heading', models.CharField(blank=True, max_length=25)),
                ('rich_text_link', models.ForeignKey(blank=True, help_text='Optional link that displays next to the heading', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('rich_text_link_text', models.CharField(blank=True, help_text='Display text for the rich text link', max_length=25)),
                ('rich_text_external_link', models.URLField(blank=True, help_text='Optional external link that displays next to the heading')),
                ('change_to_callout', models.BooleanField(default=False)),
                ('external_news_page', models.URLField(blank=True, help_text='Link to an external news page, e.g. wordpress')),
                ('internal_news_page', models.ForeignKey(blank=True, help_text='Link to an internal news page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('banner_image', models.ForeignKey(blank=True, help_text='Banners should be approximately 1200 × 200 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('banner_title', models.CharField(blank=True, max_length=100)),
                ('banner_subtitle', models.CharField(blank=True, max_length=100)),
                ('banner_feature', models.ForeignKey(blank=True, help_text='Banner feature images should be approximately 500 × 500 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
