# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('findingaids', '0009_findingaidspage_active_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaidspage',
            name='rich_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Should be a bulleted list or combination of h3 elements and bulleted lists'),
        ),
        migrations.AddField(
            model_name='findingaidspage',
            name='rich_text_heading',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='findingaidspage',
            name='rich_text_link',
            field=models.ForeignKey(blank=True, help_text='Optional link that displays next to the heading', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='findingaidspage',
            name='rich_text_link_text',
            field=models.CharField(blank=True, help_text='Display text for the rich text link', max_length=25),
        ),
    ]
