# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findingaids', '0012_findingaidspage_change_to_callout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findingaidspage',
            name='active_tag',
        ),
    ]
