# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertindexpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alertpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
