# Generated by Django 2.0.12 on 2019-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20180327_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertindexpage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertpage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
    ]
