# Generated by Django 2.0.12 on 2019-09-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20190710_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertindexpage',
            name='news_feed_url',
        ),
        migrations.RemoveField(
            model_name='alertpage',
            name='news_feed_url',
        ),
    ]
