# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20161103_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertindexpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertindexpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='alertindexpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertindexpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='alertindexpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertindexpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='alertpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='alertpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='alertpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertpage_maintainer', to='staff.StaffPage'),
        ),
    ]
