# Generated by Django 2.0.12 on 2020-03-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_21870218_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertpage',
            name='alert_level',
            field=models.CharField(choices=[('alert-info', 'Informational Alert'), ('alert-low', 'General Alert'), ('alert-high', 'Critical Alert')], default='alert-info', max_length=25),
        ),
    ]
