# Generated by Django 3.0.6 on 2020-05-28 21:22

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_auto_20200307_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertindexpage',
            name='cgi_mail_form',
            field=models.TextField(blank=True, help_text='JSON representing the fields of a form. Must follow a strict schema. Contact DLDC for help with this'),
        ),
        migrations.AddField(
            model_name='alertindexpage',
            name='cgi_mail_form_thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display after the form has been submitted'),
        ),
        migrations.AddField(
            model_name='alertpage',
            name='cgi_mail_form',
            field=models.TextField(blank=True, help_text='JSON representing the fields of a form. Must follow a strict schema. Contact DLDC for help with this'),
        ),
        migrations.AddField(
            model_name='alertpage',
            name='cgi_mail_form_thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display after the form has been submitted'),
        ),
    ]
