# Generated by Django 5.0.10 on 2025-05-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0012_alertindexpage_exclude_from_search_engines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertindexpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alertpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
    ]
