# Generated by Django 5.2.8 on 2025-11-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0012_alertindexpage_exclude_from_search_engines_and_more"),
        ("units", "0016_alter_unitindexpage_editor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertindexpage",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
        migrations.AlterField(
            model_name="alertpage",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
    ]
