# Generated by Django 5.2.9 on 2026-01-21 22:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mylib_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="auto_renewal_notice",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<b>Auto-renewal is enabled.</b> Items will be automatically renewed up to 5 times unless recalled or you have fines over $25.",
                help_text="Dismissible notice shown at top of dashboard. Leave blank to hide the notice.",
            ),
        ),
    ]
