# Generated by Django 5.2.9 on 2026-01-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mylib_dashboard", "0002_add_auto_renewal_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="max_items_per_card",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum items to show per category card before showing '+X more items'. Set to 0 to show all items.",
            ),
        ),
    ]
