# Generated by Django 5.2.9 on 2026-01-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mylib_dashboard", "0003_add_max_items_per_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="accounts_faq_url",
            field=models.URLField(
                blank=True,
                default="https://www.lib.uchicago.edu/borrow/borrowing/my-accounts/",
                help_text="URL to the Accounts FAQ page.",
            ),
        ),
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="catalog_account_url",
            field=models.URLField(
                blank=True,
                default="https://catalog.lib.uchicago.edu/vufind/MyResearch/Home",
                help_text="URL to the library catalog account page (e.g., VuFind My Account).",
            ),
        ),
    ]
