# Generated by Django 5.2.12 on 2026-04-29 19:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mylib_dashboard", "0004_add_url_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="empty_state_appointments",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="No upcoming appointments",
                help_text="Message shown in this card when the user has no items in this category.",
            ),
        ),
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="empty_state_downloads",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="No downloads available",
                help_text="Message shown in this card when the user has no items in this category.",
            ),
        ),
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="empty_state_ill_in_process",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="No ILL requests in process",
                help_text="Message shown in this card when the user has no items in this category.",
            ),
        ),
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="empty_state_material_requests",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="No material requests",
                help_text="Message shown in this card when the user has no items in this category.",
            ),
        ),
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="empty_state_non_renewable_loans",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="No non-renewable loans",
                help_text="Message shown in this card when the user has no items in this category.",
            ),
        ),
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="empty_state_paging_requests",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="No paging requests in process",
                help_text="Message shown in this card when the user has no items in this category.",
            ),
        ),
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="empty_state_pickups",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="No items available for pickup",
                help_text="Message shown in this card when the user has no items in this category.",
            ),
        ),
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="empty_state_reading_room_reservations",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="No upcoming reading room reservations",
                help_text="Message shown in this card when the user has no items in this category.",
            ),
        ),
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="empty_state_room_reservations",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="No upcoming room reservations",
                help_text="Message shown in this card when the user has no items in this category.",
            ),
        ),
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="empty_state_scan_deliver",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="No scan requests in process",
                help_text="Message shown in this card when the user has no items in this category.",
            ),
        ),
        migrations.AddField(
            model_name="mylibdashboardpage",
            name="empty_state_standard_loans",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="No standard loans",
                help_text="Message shown in this card when the user has no items in this category.",
            ),
        ),
    ]
