# Generated by Django 2.2.10 on 2020-03-27 23:43

from django.db import migrations, models
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReusableContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A friendly name only used in the Wagtail admin', max_length=155)),
                ('sidebar_heading', models.CharField(blank=True, help_text='An optional header that will display above your         content as an <h3> in the right sidebar. Ignored in page bodies', max_length=100)),
                ('content', wagtail.core.fields.RichTextField(help_text='Reusable content that can be displayed in the right         sidebar or a page body')),
            ],
            options={
                'verbose_name': 'Reusable Content',
                'verbose_name_plural': 'Reusable Content',
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
    ]
