# Generated by Django 3.0.6 on 2020-09-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable_content', '0002_reusablecontent_make_page_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reusablecontent',
            name='make_page_alert',
        ),
        migrations.AddField(
            model_name='reusablecontent',
            name='style_type',
            field=models.CharField(choices=[('general-box', 'General'), ('info-box', 'Informative'), ('alert-box', 'Alert')], default='general-box', help_text='"Informative" and "Alert" styling only applies when box is placed in-page. Styling will not apply to sidebar placement.', max_length=12, verbose_name='In-Page Styling'),
        ),
    ]
