# Generated by Django 3.0.6 on 2020-09-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable_content', '0003_auto_20200915_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reusablecontent',
            name='style_type',
            field=models.CharField(choices=[('general-box', 'General'), ('info-box', 'Informative'), ('alert-box', 'Alert')], default='general-box', help_text='"Informative" is a light blue background and "Alert" is a light red background', max_length=12, verbose_name='Styling'),
        ),
    ]
