# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:01
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20170926_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='featured_library_expert_fallback',
            field=wagtail.wagtailcore.fields.StreamField((('person', wagtail.wagtailcore.blocks.StructBlock((('library_expert', wagtail.wagtailcore.blocks.PageChooserBlock(help_text='Be sure to select a StaffPage (not a StaffPublicPage)', required=False)), ('libguides', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=False)), ('link_external', wagtail.wagtailcore.blocks.URLBlock(required=False)), ('link_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)))), icon='link'))), icon='view', required=False, template='public/blocks/featured_library_expert.html')),), blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='featured_library_experts',
            field=wagtail.wagtailcore.fields.StreamField((('person', wagtail.wagtailcore.blocks.StructBlock((('library_expert', wagtail.wagtailcore.blocks.PageChooserBlock(help_text='Be sure to select a StaffPage (not a StaffPublicPage)', required=False)), ('libguides', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=False)), ('link_external', wagtail.wagtailcore.blocks.URLBlock(required=False)), ('link_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)))), icon='link')), ('start_date', wagtail.wagtailcore.blocks.DateBlock(blank=True, null=True)), ('end_date', wagtail.wagtailcore.blocks.DateBlock(blank=True, null=True))), icon='view', required=False, template='public/blocks/featured_library_expert.html')),), blank=True, default=[]),
        ),
    ]
