# Generated by Django 2.0.3 on 2018-03-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20171121_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_donorpage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='floorplanpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_floorplanpage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='parent_building',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_building': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.LocationPage'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_locationpage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='publicrawhtmlpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_publicrawhtmlpage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='staffpublicpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_staffpublicpage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_standardpage_related', to='units.UnitPage'),
        ),
    ]
