# Generated by Django 2.0.12 on 2019-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_locationpage_is_special_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorpage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='floorplanpage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicrawhtmlpage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpublicpage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
    ]
