# Generated by Django 2.0.12 on 2019-09-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_auto_20190801_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorpage',
            name='news_feed_url',
        ),
        migrations.RemoveField(
            model_name='floorplanpage',
            name='news_feed_url',
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='news_feed_url',
        ),
        migrations.RemoveField(
            model_name='publicrawhtmlpage',
            name='news_feed_url',
        ),
        migrations.RemoveField(
            model_name='staffpublicpage',
            name='news_feed_url',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='news_feed_url',
        ),
    ]
