# Generated by Django 3.0.6 on 2020-05-28 21:22

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_auto_20200514_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorpage',
            name='cgi_mail_form',
            field=models.TextField(blank=True, help_text='JSON representing the fields of a form. Must follow a strict schema. Contact DLDC for help with this'),
        ),
        migrations.AddField(
            model_name='donorpage',
            name='cgi_mail_form_thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text to display after the form has been submitted'),
        ),
        migrations.AddField(
            model_name='floorplanpage',
            name='cgi_mail_form',
            field=models.TextField(blank=True, help_text='JSON representing the fields of a form. Must follow a strict schema. Contact DLDC for help with this'),
        ),
        migrations.AddField(
            model_name='floorplanpage',
            name='cgi_mail_form_thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text to display after the form has been submitted'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='cgi_mail_form',
            field=models.TextField(blank=True, help_text='JSON representing the fields of a form. Must follow a strict schema. Contact DLDC for help with this'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='cgi_mail_form_thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text to display after the form has been submitted'),
        ),
        migrations.AddField(
            model_name='publicrawhtmlpage',
            name='cgi_mail_form',
            field=models.TextField(blank=True, help_text='JSON representing the fields of a form. Must follow a strict schema. Contact DLDC for help with this'),
        ),
        migrations.AddField(
            model_name='publicrawhtmlpage',
            name='cgi_mail_form_thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text to display after the form has been submitted'),
        ),
        migrations.AddField(
            model_name='staffpublicpage',
            name='cgi_mail_form',
            field=models.TextField(blank=True, help_text='JSON representing the fields of a form. Must follow a strict schema. Contact DLDC for help with this'),
        ),
        migrations.AddField(
            model_name='staffpublicpage',
            name='cgi_mail_form_thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text to display after the form has been submitted'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='cgi_mail_form',
            field=models.TextField(blank=True, help_text='JSON representing the fields of a form. Must follow a strict schema. Contact DLDC for help with this'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='cgi_mail_form_thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text to display after the form has been submitted'),
        ),
    ]
