# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0018_locationpage_location_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='has_board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_book_scanner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_carrels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_cps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_dual_monitors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_large_tables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_lockers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_natural_light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_public_computer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_screen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_single_tables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_soft_seating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='has_standing_desk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='is_24_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='is_collaboration_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='is_event_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='is_meal_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='is_no_food_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='is_phone_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='is_quiet_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='is_reservable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='is_snacks_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='is_study_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='is_teaching_space',
            field=models.BooleanField(default=False),
        ),
    ]
