# Generated by Django 3.0.6 on 2020-09-22 15:37

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0019_auto_20200807_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplanpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
