# Generated by Django 3.1.12 on 2021-07-26 20:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0024_auto_20210706_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='page_alerts',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('reusable_content_block', wagtail.blocks.StructBlock([('content', wagtail.snippets.blocks.SnippetChooserBlock('reusable_content.ReusableContent'))])), ('html', wagtail.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
