# Generated by Django 3.1.12 on 2021-09-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0025_locationpage_page_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='more_icons_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='more_icons_link_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='widget_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
