# Generated by Django 3.1.12 on 2021-09-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0026_auto_20210929_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='more_icons_link',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='View More Link'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='more_icons_link_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='View More Link Label'),
        ),
    ]
