# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0026_auto_20151228_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationpage',
            old_name='description',
            new_name='short_description',
        ),
    ]
