# Generated by Django 3.1.12 on 2021-12-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0027_auto_20210929_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='has_all_gender_restrooms',
            field=models.BooleanField(default=False),
        ),
    ]
