# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 18:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0027_auto_20160119_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='long_description',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
