# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0028_locationpage_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpage',
            name='library_floorplan_link',
        ),
    ]
