# Generated by Django 3.1.12 on 2022-01-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0028_locationpage_has_all_gender_restrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='expert_link',
            field=models.URLField(default='https://your.library.here', max_length=300),
        ),
    ]
