# Generated by Django 3.1.12 on 2022-03-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0029_standardpage_expert_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='expert_link',
            field=models.URLField(default='/', max_length=300, verbose_name='Featured Expert Link'),
        ),
    ]
