# Generated by Django 3.1.12 on 2022-03-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0030_auto_20220304_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='expert_link',
            field=models.CharField(default='/about/directory/?view=staff', max_length=400, verbose_name='Featured Expert Link'),
        ),
    ]
