# Generated by Django 5.0.10 on 2025-05-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0036_donorpage_exclude_from_search_engines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donorpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="floorplanpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="locationpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publicrawhtmlpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffpublicpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
    ]
