# Generated by Django 5.2.8 on 2025-11-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0038_alter_standardpage_body"),
        ("units", "0016_alter_unitindexpage_editor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorpage",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
        migrations.AlterField(
            model_name="floorplanpage",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
        migrations.AlterField(
            model_name="locationpage",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
        migrations.AlterField(
            model_name="publicrawhtmlpage",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
        migrations.AlterField(
            model_name="staffpublicpage",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
    ]
