# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0044_auto_20160225_1843'),
        ('public', '0043_auto_20160301_1838'),
    ]

    operations = [
    ]
