# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0045_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpage',
            name='has_cps',
        ),
    ]
