# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 15:20
from __future__ import unicode_literals

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0046_remove_locationpage_has_cps'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='quicklinks',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
