# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0047_standardpage_quicklinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='quicklinks_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='view_more_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='view_more_link_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
