# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 15:36
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0048_auto_20160318_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='quicklinks',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
