# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0049_auto_20160318_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='blog_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='facebook_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='hashtag',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='hashtag_page',
            field=models.URLField(blank=True, help_text='Link to twitter page using a hashtag'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='instagram_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='snapchat_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='tumbler_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='twitter_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='youtube_page',
            field=models.URLField(blank=True),
        ),
    ]
