# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0051_auto_20160318_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_donorpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='donorpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_donorpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='donorpage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_donorpage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='floorplanpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_floorplanpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='floorplanpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_floorplanpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='floorplanpage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_floorplanpage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_locationpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_locationpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_locationpage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_standardpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_standardpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_standardpage_related', to='units.UnitPage'),
        ),
    ]
