# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0052_auto_20160328_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='book_a_room_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='collaboration_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='quiet_study_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
