# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0053_auto_20160503_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='collaboration_link',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='quiet_study_link',
        ),
        migrations.AddField(
            model_name='standardpage',
            name='enable_find_spaces',
            field=models.BooleanField(default=False),
        ),
    ]
