# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('public', '0054_auto_20160506_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='collection_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
