# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0055_standardpage_collection_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='collection_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lib_collections.CollectionPage'),
        ),
    ]
