# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 18:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0056_auto_20160509_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='featured_library_expert_fallback',
            field=wagtail.core.fields.StreamField((('person', wagtail.core.blocks.StructBlock((('library_expert', wagtail.core.blocks.PageChooserBlock(required=False)), ('libguides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('link_text', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('link_external', wagtail.core.blocks.URLBlock(required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)))), icon='link'))), icon='view', required=False, template='public/blocks/featured_library_expert.html')),), default=[]),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='featured_library_experts',
            field=wagtail.core.fields.StreamField((('person', wagtail.core.blocks.StructBlock((('library_expert', wagtail.core.blocks.PageChooserBlock(required=False)), ('libguides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('link_text', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('link_external', wagtail.core.blocks.URLBlock(required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)))), icon='link')), ('start_date', wagtail.core.blocks.DateBlock(blank=True, null=True)), ('end_date', wagtail.core.blocks.DateBlock(blank=True, null=True))), icon='view', required=False, template='public/blocks/featured_library_expert.html')),), default=[]),
        ),
    ]
