# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0062_auto_20160602_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='enable_search_widget',
            field=models.BooleanField(default=False),
        ),
    ]
