# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('public', '0066_auto_20160609_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Banners should be approximately 1200 × 200 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
