# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0067_auto_20160609_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='floorplanpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='publicrawhtmlpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='staffpublicpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='sort_order',
        ),
    ]
