# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0071_auto_20160621_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorpage',
            name='display_hierarchical_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorpage',
            name='enable_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='floorplanpage',
            name='display_hierarchical_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='floorplanpage',
            name='enable_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='display_hierarchical_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='enable_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicrawhtmlpage',
            name='display_hierarchical_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicrawhtmlpage',
            name='enable_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpublicpage',
            name='display_hierarchical_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpublicpage',
            name='enable_index',
            field=models.BooleanField(default=False),
        ),
    ]
