# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0073_auto_20160623_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpage',
            name='events_feed_url',
            field=models.URLField(blank=True, help_text='Link to a Tiny Tiny RSS Feed'),
        ),
        migrations.AlterField(
            model_name='floorplanpage',
            name='events_feed_url',
            field=models.URLField(blank=True, help_text='Link to a Tiny Tiny RSS Feed'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='events_feed_url',
            field=models.URLField(blank=True, help_text='Link to a Tiny Tiny RSS Feed'),
        ),
        migrations.AlterField(
            model_name='publicrawhtmlpage',
            name='events_feed_url',
            field=models.URLField(blank=True, help_text='Link to a Tiny Tiny RSS Feed'),
        ),
        migrations.AlterField(
            model_name='staffpublicpage',
            name='events_feed_url',
            field=models.URLField(blank=True, help_text='Link to a Tiny Tiny RSS Feed'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='events_feed_url',
            field=models.URLField(blank=True, help_text='Link to a Tiny Tiny RSS Feed'),
        ),
    ]
