# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0075_auto_20160627_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorpage',
            name='active_tag',
            field=models.CharField(blank=True, help_text='A WordPress tag name used for display purposes, e.g. "Library Kiosk"', max_length=30),
        ),
        migrations.AddField(
            model_name='floorplanpage',
            name='active_tag',
            field=models.CharField(blank=True, help_text='A WordPress tag name used for display purposes, e.g. "Library Kiosk"', max_length=30),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='active_tag',
            field=models.CharField(blank=True, help_text='A WordPress tag name used for display purposes, e.g. "Library Kiosk"', max_length=30),
        ),
        migrations.AddField(
            model_name='publicrawhtmlpage',
            name='active_tag',
            field=models.CharField(blank=True, help_text='A WordPress tag name used for display purposes, e.g. "Library Kiosk"', max_length=30),
        ),
        migrations.AddField(
            model_name='staffpublicpage',
            name='active_tag',
            field=models.CharField(blank=True, help_text='A WordPress tag name used for display purposes, e.g. "Library Kiosk"', max_length=30),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='active_tag',
            field=models.CharField(blank=True, help_text='A WordPress tag name used for display purposes, e.g. "Library Kiosk"', max_length=30),
        ),
    ]
