# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0078_auto_20160629_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorpage',
            name='change_to_callout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='floorplanpage',
            name='change_to_callout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='change_to_callout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicrawhtmlpage',
            name='change_to_callout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpublicpage',
            name='change_to_callout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='change_to_callout',
            field=models.BooleanField(default=False),
        ),
    ]
