# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0080_standardpagecarouselitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpagecarouselitem',
            name='link_url',
        ),
    ]
