# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0081_remove_standardpagecarouselitem_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorpage',
            name='active_tag',
        ),
        migrations.RemoveField(
            model_name='floorplanpage',
            name='active_tag',
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='active_tag',
        ),
        migrations.RemoveField(
            model_name='publicrawhtmlpage',
            name='active_tag',
        ),
        migrations.RemoveField(
            model_name='staffpublicpage',
            name='active_tag',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='active_tag',
        ),
    ]
