# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0085_auto_20160708_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpagecarouselitem',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Suggested proportions: 1200px wide by 400px high ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
