# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0087_auto_20160802_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='floorplanpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publicrawhtmlpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffpublicpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
