# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0097_auto_20161103_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_donorpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='donorpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_donorpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='donorpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_donorpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='floorplanpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_floorplanpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='floorplanpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_floorplanpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='floorplanpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_floorplanpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_locationpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_locationpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_locationpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='publicrawhtmlpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_publicrawhtmlpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='publicrawhtmlpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_publicrawhtmlpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='publicrawhtmlpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_publicrawhtmlpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='staffpublicpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_staffpublicpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='staffpublicpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_staffpublicpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='staffpublicpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_staffpublicpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_standardpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_standardpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_standardpage_maintainer', to='staff.StaffPage'),
        ),
    ]
