# Generated by Django 2.2.10 on 2020-03-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False, help_text='Checking this box will enable "Emergency Hours" and                    replace the hours dropdown in the public website header')),
                ('link_text', models.CharField(blank=True, help_text='Optional hours link text to display in the header.                    Defaults to "View Hours" if nothing is set', max_length=35)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
