# Generated by Django 5.2.6 on 2025-10-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0003_staffsyncsettings_excludedcnetid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffsyncsettings",
            name="site",
        ),
    ]
