# Generated by Django 5.2.8 on 2025-11-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0004_remove_staffsyncsettings_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsFeedSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_visible",
                    models.PositiveIntegerField(
                        default=9,
                        help_text="Number of news items to display initially on the news index page",
                    ),
                ),
                (
                    "increment_by",
                    models.PositiveIntegerField(
                        default=12,
                        help_text='Number of additional news items to load when "Load More" is clicked',
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
