# Generated by Django 5.2.8 on 2025-11-06 22:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0005_newsfeedsettings"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickNumberGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='Identifier for this group (e.g., "the-joseph-regenstein-library")',
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for this group", max_length=255
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this group as the default fallback when no specific quick numbers are found",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick Numbers Group",
                "verbose_name_plural": "Quick Numbers Groups",
            },
        ),
        migrations.CreateModel(
            name="QuickNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Display label (e.g., "Main Telephone", "Circulation")',
                        max_length=100,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text='Phone number (e.g., "773-702-8740")',
                        max_length=20,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional page link instead of phone number",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "group",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numbers",
                        to="site_settings.quicknumbergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
