# Generated by Django 3.0.7 on 2021-01-14 00:46

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200807_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='intranetplainpage',
            name='cgi_mail_form',
            field=models.TextField(blank=True, help_text='JSON representing the fields of a form. Must follow a strict schema. Contact DLDC for help with this'),
        ),
        migrations.AddField(
            model_name='intranetplainpage',
            name='cgi_mail_form_thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display after the form has been submitted'),
        ),
    ]
