# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.search.index


class Migration(migrations.Migration):

    replaces = [('subjects', '0001_initial'), ('subjects', '0002_auto_20160120_2304'), ('subjects', '0003_subject_libguide_url'), ('subjects', '0004_subjectseealsotable'), ('subjects', '0005_auto_20160506_1529'), ('subjects', '0006_subject_display_in_dropdown')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('libguide_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='SubjectParentRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('child', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_subject', to='subjects.Subject')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='subjects.Subject')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SubjectSeeAlsoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alias', models.CharField(max_length=255)),
                ('snippet', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='see_also', to='subjects.Subject')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='display_in_dropdown',
            field=models.BooleanField(default=False),
        ),
    ]
