# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectParentRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='parent',
        ),
        migrations.AddField(
            model_name='subjectparentrelations',
            name='child',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_subject', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='subjectparentrelations',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='subjects.Subject'),
        ),
    ]
