# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20160120_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='libguide_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
