# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_libguide_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSeeAlsoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alias', models.CharField(max_length=255)),
                ('snippet', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='see_also', to='subjects.Subject')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
