# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20160506_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='display_in_dropdown',
            field=models.BooleanField(default=False),
        ),
    ]
