# Generated by Django 2.0.12 on 2019-08-01 21:18

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lib_news', '0002_auto_20190801_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='libnewsindexpage',
            name='navigation',
            field=wagtail.core.fields.StreamField([('navigation', wagtail.core.blocks.PageChooserBlock(page_type=['lib_news.LibNewsPage'], required=False))], default=[]),
        ),
    ]
