# Generated by Django 2.0.12 on 2019-08-21 23:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('lib_news', '0003_libnewsindexpage_navigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicNewsAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link_external', models.URLField(blank=True, max_length=400, null=True)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Public News Author',
                'verbose_name_plural': 'Public News Authors',
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.RemoveField(
            model_name='libnewspage',
            name='by_staff',
        ),
        migrations.RemoveField(
            model_name='libnewspage',
            name='by_unit',
        ),
        migrations.AddField(
            model_name='libnewspage',
            name='by_staff_or_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lib_news.PublicNewsAuthors'),
        ),
    ]
