# Generated by Django 2.0.12 on 2019-08-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_news', '0004_auto_20190821_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicnewsauthors',
            old_name='name',
            new_name='author_name',
        ),
    ]
