# Generated by Django 2.0.12 on 2019-08-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_news', '0005_auto_20190821_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libnewspage',
            name='by_text_box',
            field=models.CharField(blank=True, max_length=360),
        ),
    ]
