# Generated by Django 2.0.12 on 2019-09-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_news', '0006_auto_20190826_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libnewspage',
            old_name='by_text_box',
            new_name='custom_author_byline',
        ),
    ]
