# Generated by Django 2.0.12 on 2019-09-10 15:41

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lib_news', '0007_auto_20190905_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='libnewspage',
            name='exhibit_story_hours_override',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
