# Generated by Django 2.0.12 on 2019-09-17 21:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lib_news', '0008_libnewspage_exhibit_story_hours_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libnewsindexpage',
            name='navigation',
            field=wagtail.core.fields.StreamField([('navigation', wagtail.core.blocks.PageChooserBlock(page_type=['lib_news.LibNewsPage'], required=False))], blank=True, default=[], null=True),
        ),
    ]
