# Generated by Django 2.0.12 on 2187-02-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_news', '0011_auto_20190924_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libnewspage',
            old_name='crerar_kiosk',
            new_name='sciences_kiosk',
        ),
        migrations.AlterField(
            model_name='libnewsindexpage',
            name='news_feed_source',
            field=models.CharField(blank=True, choices=[('', '--------'), ('library_kiosk', 'Library'), ('law_kiosk', 'Law'), ('sciences_kiosk', 'Sciences'), ('scrc_kiosk', 'SCRC')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='libnewspage',
            name='news_feed_source',
            field=models.CharField(blank=True, choices=[('', '--------'), ('library_kiosk', 'Library'), ('law_kiosk', 'Law'), ('sciences_kiosk', 'Sciences'), ('scrc_kiosk', 'SCRC')], default='', max_length=50),
        ),
    ]
