# Generated by Django 3.1.12 on 2021-07-02 19:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lib_news', '0018_auto_20210303_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libnewspage',
            name='related_exhibits',
            field=wagtail.fields.StreamField([('exhibit', wagtail.blocks.StructBlock([('exhibit', wagtail.blocks.PageChooserBlock(help_text='Select an ExhibitPage', page_type=['lib_collections.ExhibitPage'], required=False))], icon='view', required=False, template='public/blocks/related_exhibit.html'))], blank=True, default=[]),
        ),
    ]
