# Generated by Django 4.1.13 on 2024-04-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib_news", "0023_libnewspage_cds_kiosk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libnewspage",
            name="cds_kiosk",
            field=models.BooleanField(default=False, verbose_name="CDS kiosk"),
        ),
        migrations.AlterField(
            model_name="libnewspage",
            name="scrc_kiosk",
            field=models.BooleanField(default=False, verbose_name="SCRC kiosk"),
        ),
    ]
