# Generated by Django 5.2.8 on 2025-11-10 19:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lib_news", "0026_alter_libnewspage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libnewspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 1),
                    ("h2", 2),
                    ("h3", 3),
                    ("h4", 4),
                    ("h5", 5),
                    ("columns_block", 7),
                    ("blockquote", 10),
                    ("pullquote", 11),
                    ("reusable_content", 13),
                    ("image", 21),
                    ("solo_image", 24),
                    ("duo_image", 27),
                    ("local_media", 28),
                    ("video_with_title", 31),
                    ("button", 37),
                    ("image_link", 42),
                    ("staff_listing", 48),
                    ("anchor_target", 50),
                    ("table", 51),
                    ("agenda_item", 59),
                    ("clear", 60),
                    ("code", 63),
                    ("html", 64),
                ],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.StructBlock",
                        [[("paragraph", 0)]],
                        {"group": "Format and Text"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "Format and Text",
                            "icon": "title",
                            "template": "base/blocks/h2.html",
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "Format and Text",
                            "icon": "title",
                            "template": "base/blocks/h3.html",
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "Format and Text",
                            "icon": "title",
                            "template": "base/blocks/h4.html",
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "Format and Text",
                            "icon": "title",
                            "template": "base/blocks/h5.html",
                        },
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "arrow-right", "label": "New Column"},
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("new_column", 6)]],
                        {"group": "Format and Text"},
                    ),
                    8: ("wagtail.blocks.TextBlock", ("quote title",), {}),
                    9: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 8), ("attribution", 9)]],
                        {"group": "Format and Text"},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 0)]],
                        {"group": "Format and Text"},
                    ),
                    12: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("reusable_content.ReusableContent",),
                        {},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 12)]],
                        {"group": "Format and Text"},
                    ),
                    14: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Photographer, artist, or creator of image",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Details about or description of image",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Required for ADA compliance", "required": True},
                    ),
                    18: ("base.models.ImageFormatChoiceBlock", (), {}),
                    19: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to image source (needed for Creative Commons)",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Link to a larger version of the image",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 14),
                                ("title", 9),
                                ("citation", 15),
                                ("caption", 16),
                                ("alt_text", 17),
                                ("alignment", 18),
                                ("source", 19),
                                ("lightbox", 20),
                            ]
                        ],
                        {"group": "Images and Media", "label": "Image"},
                    ),
                    22: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"blank": True, "null": True, "required": False},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Required for ADA compliance if no caption or citation is provided",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 14),
                                ("citation", 22),
                                ("caption", 22),
                                ("alt_text", 23),
                            ]
                        ],
                        {
                            "group": "Images and Media",
                            "help_text": "Single image with caption on the right",
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 14),
                                ("citation", 22),
                                ("caption", 22),
                                ("alt_text", 23),
                            ]
                        ],
                        {
                            "help_text": "First of two images displayed             side by side"
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 14),
                                ("citation", 22),
                                ("caption", 22),
                                ("alt_text", 23),
                            ]
                        ],
                        {
                            "help_text": "Second of two images displayed             side by side"
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("image_one", 25), ("image_two", 26)]],
                        {
                            "group": "Images and Media",
                            "help_text": "Two images side by side with captions below",
                        },
                    ),
                    28: (
                        "base.models.LocalMediaBlock",
                        (),
                        {
                            "group": "Images and Media",
                            "help_text": "Audio or video files that have been uploaded into Wagtail",
                            "label": "Video or Audio",
                        },
                    ),
                    29: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Video URL from YouTube or Vimeo",
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Descriptive title for screen readers (e.g., "Introduction to Python Programming")',
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 29), ("title", 30)]],
                        {
                            "group": "Images and Media",
                            "icon": "media",
                            "label": "External Video with Title",
                        },
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("btn-primary", "Primary"),
                                ("btn-default", "Secondary"),
                                ("btn-reserve", "Reservation"),
                            ]
                        },
                    ),
                    33: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    34: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    35: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    36: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_type", 32),
                                ("button_text", 33),
                                ("link_external", 34),
                                ("link_page", 35),
                                ("link_document", 36),
                            ]
                        ],
                        {"group": "Links"},
                    ),
                    38: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Required if no link text supplied for ADA compliance",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Font Awesome icon name if you're not using an image",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to display below the image or icon",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 38),
                                ("alt_text", 39),
                                ("icon", 40),
                                ("link_text", 41),
                                ("link_external", 34),
                                ("link_page", 35),
                                ("link_document", 36),
                            ]
                        ],
                        {
                            "group": "Links",
                            "help_text": "A fancy link made out of a thumbnail and simple text",
                            "label": "Linked Image",
                        },
                    ),
                    43: ("wagtail.blocks.PageChooserBlock", (), {}),
                    44: (
                        "wagtail.blocks.ListBlock",
                        (43,),
                        {
                            "help_text": "Be sure to select staff pages from Loop.",
                            "icon": "edit",
                            "label": "Staff listing",
                        },
                    ),
                    45: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show staff photographs.",
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show contact information.",
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show subject specialties.",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("staff_listing", 44),
                                ("show_photos", 45),
                                ("show_contact_info", 46),
                                ("show_subject_specialties", 47),
                            ]
                        ],
                        {
                            "group": "Links",
                            "help_text": "Automatically displays selected staff with title, contact, and link to staff profile page",
                            "icon": "group",
                            "template": "base/blocks/staff_listing.html",
                        },
                    ),
                    49: ("wagtail.blocks.CharBlock", (), {"max_length": 50}),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("anchor_id_name", 49)]],
                        {
                            "group": "Links",
                            "help_text": 'Where you want an anchor link to jump to. Must exactly match the "#" label supplied in anchor link (found in Paragraph streamfield).',
                        },
                    ),
                    51: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "group": "Layout and Data",
                            "help_text": 'Right + click in a table cell for more options. Use <em>text</em> for italics, <strong>text</strong> for bold, and <a href="https://duckduckgo.com">text</a> for links.',
                            "table_options": {
                                "autoColumnSize": False,
                                "colHeaders": False,
                                "editor": "text",
                                "height": 108,
                                "language": "en",
                                "minSpareRows": 0,
                                "renderer": "html",
                                "rowHeaders": False,
                                "startCols": 3,
                                "startRows": 3,
                                "stretchH": "all",
                            },
                            "template": "base/blocks/table.html",
                        },
                    ),
                    52: (
                        "wagtail.blocks.TimeBlock",
                        (),
                        {"icon": "time", "required": False},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title of the session.             Can be used as title of the talk in some situations.",
                            "icon": "title",
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Talk title, workshop title, etc.",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Comma separated list of presenters             (if more than one)",
                            "required": False,
                        },
                    ),
                    56: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 54),
                                ("presenters", 55),
                                ("room_number", 9),
                                ("description", 56),
                            ]
                        ],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.ListBlock",
                        (57,),
                        {
                            "help_text": "A talk or event with a title, presenter             room number, and description",
                            "icon": "edit",
                            "label": " ",
                        },
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("start_time", 52),
                                ("end_time", 52),
                                ("session_title", 53),
                                ("event", 58),
                            ]
                        ],
                        {
                            "group": "Layout and Data",
                            "icon": "date",
                            "template": "base/blocks/agenda.html",
                        },
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[]],
                        {
                            "group": "Layout and Data",
                            "help_text": "Resets layout before or after floated images.",
                            "lable": "Clear Formatting",
                        },
                    ),
                    61: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("ocaml", "OCaml"),
                                ("php5", "PHP"),
                                ("html+php", "PHP/HTML"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ]
                        },
                    ),
                    62: ("wagtail.blocks.TextBlock", (), {}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 61), ("code", 62)]],
                        {"group": "Layout and Data"},
                    ),
                    64: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "group": "Layout and Data",
                            "help_text": "Display code as text for tutorial or documentation purposes",
                        },
                    ),
                },
            ),
        ),
    ]
