# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 15:51
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('public', '0004_auto_20170705_1130'),
        ('lib_collections', '0004_auto_20170705_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingareapagestacksranges',
            name='page',
        ),
        migrations.RemoveField(
            model_name='collectingareareferencelocationplacement',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='collectingareareferencelocationplacement',
            name='related_collection',
        ),
        migrations.RemoveField(
            model_name='highlightedcollectionsplacement',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='highlightedcollectionsplacement',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subjectspecialistplacement',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subjectspecialistplacement',
            name='subject_specialist',
        ),
        migrations.AlterModelOptions(
            name='exhibitpagesubjectplacement',
            options={'verbose_name': 'Subject Placement', 'verbose_name_plural': 'Subject Placements'},
        ),
        migrations.RenameField(
            model_name='regionalcollectionplacements',
            old_name='collection_description',
            new_name='regional_collection_description',
        ),
        migrations.RenameField(
            model_name='regionalcollectionplacements',
            old_name='collection_name',
            new_name='regional_collection_name',
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='archival_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='archival_link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Archival URL'),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='circulating_materials',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='collection_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.LocationPage'),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='first_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='fourth_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='policy_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='policy_link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Policy URL'),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='reference_materials',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='related_collecting_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='second_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='short_abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='supplementary_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='supplementary_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='third_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='regionalcollectionplacements',
            name='regional_collection_url',
            field=models.URLField(blank=True, null=True, verbose_name='Regional Collection URL'),
        ),
        migrations.AlterField(
            model_name='collectingareapage',
            name='collecting_statement',
            field=wagtail.core.fields.StreamField((('h2', wagtail.core.blocks.CharBlock(classname='title', icon='title', template='base/blocks/h2.html')), ('h3', wagtail.core.blocks.CharBlock(classname='title', icon='title', template='base/blocks/h3.html')), ('h4', wagtail.core.blocks.CharBlock(classname='title', icon='title', template='base/blocks/h4.html')), ('h5', wagtail.core.blocks.CharBlock(classname='title', icon='title', template='base/blocks/h5.html')), ('h6', wagtail.core.blocks.CharBlock(classname='title', icon='title', template='base/blocks/h6.html')), ('paragraph', wagtail.core.blocks.StructBlock((('paragraph', wagtail.core.blocks.RichTextBlock()),))), ('image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock(required=False)), ('citation', wagtail.core.blocks.CharBlock(help_text='Photographer, artist, or creator of image', required=False)), ('caption', wagtail.core.blocks.TextBlock(help_text='Details about or description of image', required=False)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Invisible text for screen readers', required=False)), ('alignment', base.models.ImageFormatChoiceBlock()), ('source', wagtail.core.blocks.URLBlock(help_text='Link to image source (needed for Creative Commons)', required=False)), ('lightbox', wagtail.core.blocks.BooleanBlock(default=False, help_text='Link to a larger version of the image', required=False))), label='Image')), ('blockquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.TextBlock('quote title')), ('attribution', wagtail.core.blocks.CharBlock(required=False))))), ('pullquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.RichTextBlock()),))), ('button', wagtail.core.blocks.StructBlock((('button_type', wagtail.core.blocks.ChoiceBlock(choices=[('btn-primary', 'Primary'), ('btn-default', 'Secondary'), ('btn-reserve', 'Reservation')])), ('button_text', wagtail.core.blocks.CharBlock(max_length=20)), ('link_external', wagtail.core.blocks.URLBlock(required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_document', wagtail.documents.blocks.DocumentChooserBlock(required=False))))), ('video', wagtail.embeds.blocks.EmbedBlock(icon='media')), ('code', wagtail.core.blocks.StructBlock((('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('ocaml', 'OCaml'), ('php5', 'PHP'), ('html+php', 'PHP/HTML'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')])), ('code', wagtail.core.blocks.TextBlock())))), ('agenda_item', wagtail.core.blocks.StructBlock((('start_time', wagtail.core.blocks.TimeBlock(icon='time', required=False)), ('end_time', wagtail.core.blocks.TimeBlock(icon='time', required=False)), ('session_title', wagtail.core.blocks.CharBlock(help_text='Title of the session.             Can be used as title of the talk in some situations.', icon='title', required=False)), ('event', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(help_text='Talk title, workshop title, etc.', required=False)), ('presenters', wagtail.core.blocks.CharBlock(help_text='Comma separated list of presenters             (if more than one)', required=False)), ('room_number', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)))), help_text='A talk or event with a title, presenter             room number, and description', icon='edit', label=' '))), icon='date', template='base/blocks/agenda.html')), ('clear', wagtail.core.blocks.StructBlock(())), ('table', wagtail.contrib.table_block.blocks.TableBlock(help_text='Right + click in a table cell for more options. Use <em>text</em> for italics, <strong>text</strong> for bold, and <a href="https://duckduckgo.com">text</a> for links.', table_options={'autoColumnSize': False, 'colHeaders': False, 'contextMenu': True, 'editor': 'text', 'height': 108, 'language': 'en', 'minSpareRows': 0, 'renderer': 'html', 'rowHeaders': False, 'startCols': 3, 'startRows': 3, 'stretchH': 'all'}, template='base/blocks/table.html')), ('staff_listing', wagtail.core.blocks.StructBlock((('staff_listing', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(), help_text='Be sure to select staff pages from Loop.', icon='edit', label='Staff listing')), ('show_photos', wagtail.core.blocks.BooleanBlock(default=False, help_text='Show staff photographs.', required=False)), ('show_contact_info', wagtail.core.blocks.BooleanBlock(default=False, help_text='Show contact information.', required=False)), ('show_subject_specialties', wagtail.core.blocks.BooleanBlock(default=False, help_text='Show subject specialties.', required=False))), icon='group', template='base/blocks/staff_listing.html')), ('solo_image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('citation', wagtail.core.blocks.RichTextBlock(blank=True, null=True)), ('caption', wagtail.core.blocks.RichTextBlock(blank=True, null=True, required=False)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Invisible text for screen readers', required=False))), help_text='Single image with caption on the right')), ('duo_image', wagtail.core.blocks.StructBlock((('image_one', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('citation', wagtail.core.blocks.RichTextBlock(blank=True, null=True)), ('caption', wagtail.core.blocks.RichTextBlock(blank=True, null=True, required=False)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Invisible text for screen readers', required=False))), help_text='First of two images displayed             side by side')), ('image_two', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('citation', wagtail.core.blocks.RichTextBlock(blank=True, null=True)), ('caption', wagtail.core.blocks.RichTextBlock(blank=True, null=True, required=False)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Invisible text for screen readers', required=False))), help_text='Second of two images displayed             side by side'))), help_text='Two images stacked side by side')), ('image_link', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Invisible text for screen readers', required=False)), ('icon', wagtail.core.blocks.CharBlock(help_text="Font Awesome icon name if you're not using an image", required=False)), ('link_text', wagtail.core.blocks.CharBlock(help_text='Text to display below the image or icon', required=False)), ('link_external', wagtail.core.blocks.URLBlock(required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_document', wagtail.documents.blocks.DocumentChooserBlock(required=False))), help_text='A fancy link made out of a thumnail and simple text')), ('local_media', base.models.LocalMediaBlock(help_text='Audio or video files that are locally hosted'))), null=True),
        ),
        migrations.AlterField(
            model_name='collectingareapage',
            name='guide_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collectingareapage',
            name='guide_link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Libguide URL'),
        ),
        migrations.AlterField(
            model_name='collectingareapagelibguides',
            name='guide_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collectingareapagelibguides',
            name='guide_link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Libguide URL'),
        ),
        migrations.DeleteModel(
            name='CollectingAreaPageStacksRanges',
        ),
        migrations.DeleteModel(
            name='CollectingAreaReferenceLocationPlacement',
        ),
        migrations.DeleteModel(
            name='HighlightedCollectionsPlacement',
        ),
        migrations.DeleteModel(
            name='SubjectSpecialistPlacement',
        ),
    ]
