# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0005_auto_20170808_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedCollectingAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='collectingareapage',
            name='related_collecting_area',
        ),
        migrations.AddField(
            model_name='relatedcollectingareas',
            name='parent',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_collecting_areas', to='lib_collections.CollectingAreaPage'),
        ),
        migrations.AddField(
            model_name='relatedcollectingareas',
            name='related_collecting_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_collecting_area', to='lib_collections.CollectingAreaPage'),
        ),
    ]
