# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0007_auto_20151209_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingareapage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectingareapage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='collectingareapage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectingareapage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='collectingareapage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectingareapage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectionpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectionpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectionpage_related', to='units.UnitPage'),
        ),
    ]
