# Generated by Django 2.0.3 on 2018-03-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0007_auto_20170926_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingareapage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectingareapage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectionpage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='exhibitchildpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_exhibitchildpage_related', to='units.UnitPage'),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'display_in_dropdown': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_exhibitpage_related', to='units.UnitPage'),
        ),
    ]
