# Generated by Django 2.0.12 on 2019-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0008_auto_20180327_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingareapage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitchildpage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='display_current_web_exhibits',
            field=models.BooleanField(default=False),
        ),
    ]
