# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0009_exhibitpage_exhibitpagedonorpageplacement_exhibitpagerelatedcollectionpageplacement_exhibitpagesubje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitpagesubjectplacement',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_pages', to='subjects.Subject'),
        ),
    ]
