# Generated by Django 2.0.12 on 2019-09-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0010_auto_20190801_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingareapage',
            name='news_feed_url',
        ),
        migrations.RemoveField(
            model_name='collectionpage',
            name='news_feed_url',
        ),
        migrations.RemoveField(
            model_name='exhibitchildpage',
            name='news_feed_url',
        ),
        migrations.RemoveField(
            model_name='exhibitpage',
            name='news_feed_url',
        ),
    ]
