# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0028_merge'),
        ('lib_collections', '0011_auto_20160502_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitPageExhibitChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExhibitPageExhibitText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='exhibitpage',
            name='exhibit_checklist',
        ),
        migrations.RemoveField(
            model_name='exhibitpage',
            name='exhibit_text',
        ),
        migrations.AddField(
            model_name='exhibitpageexhibittext',
            name='exhibit_text',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_text', to='lib_collections.ExhibitPage'),
        ),
        migrations.AddField(
            model_name='exhibitpageexhibittext',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='exhibitpageexhibittext',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='exhibitpageexhibitchecklist',
            name='exhibit_checklist',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_checklist', to='lib_collections.ExhibitPage'),
        ),
        migrations.AddField(
            model_name='exhibitpageexhibitchecklist',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='exhibitpageexhibitchecklist',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
