# Generated by Django 2.0.12 on 2187-02-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0012_auto_20190924_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingareapage',
            name='news_feed_source',
            field=models.CharField(blank=True, choices=[('', '--------'), ('library_kiosk', 'Library'), ('law_kiosk', 'Law'), ('sciences_kiosk', 'Sciences'), ('scrc_kiosk', 'SCRC')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='news_feed_source',
            field=models.CharField(blank=True, choices=[('', '--------'), ('library_kiosk', 'Library'), ('law_kiosk', 'Law'), ('sciences_kiosk', 'Sciences'), ('scrc_kiosk', 'SCRC')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exhibitchildpage',
            name='news_feed_source',
            field=models.CharField(blank=True, choices=[('', '--------'), ('library_kiosk', 'Library'), ('law_kiosk', 'Law'), ('sciences_kiosk', 'Sciences'), ('scrc_kiosk', 'SCRC')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='news_feed_source',
            field=models.CharField(blank=True, choices=[('', '--------'), ('library_kiosk', 'Library'), ('law_kiosk', 'Law'), ('sciences_kiosk', 'Sciences'), ('scrc_kiosk', 'SCRC')], default='', max_length=50),
        ),
    ]
