# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0015_auto_20160510_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpage',
            name='thumbnail_caption',
            field=models.TextField(blank=True),
        ),
    ]
