# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0015_auto_20160510_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPageSupplementaryAccessLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('access_link_label', models.CharField(max_length=255)),
                ('access_link_url', models.URLField(verbose_name='Access link URL')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='collectionpageaccesslinks',
            name='page',
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='primary_online_access_link_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='primary_online_access_link_url',
            field=models.URLField(blank=True, verbose_name='Primary Online Access link URL'),
        ),
        migrations.DeleteModel(
            name='CollectionPageAccessLinks',
        ),
        migrations.AddField(
            model_name='collectionpagesupplementaryaccesslinks',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_access_links', to='lib_collections.CollectionPage'),
        ),
    ]
