# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0016_auto_20160512_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionpagesupplementaryaccesslinks',
            old_name='access_link_label',
            new_name='supplementary_access_link_label',
        ),
        migrations.RenameField(
            model_name='collectionpagesupplementaryaccesslinks',
            old_name='access_link_url',
            new_name='supplementary_access_link_url',
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='primary_online_access_link_url',
            field=models.URLField(blank=True, verbose_name='Primary online access link URL'),
        ),
    ]
