# Generated by Django 2.0.12 on 2020-02-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0017_collectionpagefacet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionpageclusterbrowse',
            old_name='col_cbrowse',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='collectionpagefacet',
            old_name='col_facet',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='collectionpagelistbrowse',
            old_name='col_lbrowse',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='collectionpagesearch',
            old_name='col_search',
            new_name='label',
        ),
    ]
