# Generated by Django 2.0.12 on 2020-02-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0018_auto_20200219_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpagesearch',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default search?'),
        ),
        migrations.AddField(
            model_name='collectionpagesearch',
            name='mark_logic_parameter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
