# Generated by Django 2.0.12 on 2020-02-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0019_auto_20200219_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionpagesearch',
            old_name='is_default',
            new_name='default',
        ),
    ]
