# Generated by Django 2.0.12 on 2020-02-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0020_auto_20200219_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpagefacet',
            name='search_handler_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collectionpagesearch',
            name='search_handler_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
