# Generated by Django 2.0.12 on 2020-02-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0022_auto_20200219_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpageclusterbrowse',
            name='iiif_location',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collectionpagelistbrowse',
            name='iiif_location',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
