# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0022_auto_20160609_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingareapage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='collectionpage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='exhibitpage',
            name='sort_order',
        ),
    ]
