# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0023_auto_20160610_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingareapage',
            name='quicklinks',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='quicklinks_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='view_more_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='view_more_link_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='quicklinks',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='quicklinks_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='view_more_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='view_more_link_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='quicklinks',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='quicklinks_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='view_more_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='view_more_link_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
