# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0025_auto_20160621_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingareapage',
            name='display_hierarchical_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectingareapage',
            name='enable_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='display_hierarchical_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='enable_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='display_hierarchical_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='enable_index',
            field=models.BooleanField(default=False),
        ),
    ]
