# Generated by Django 2.0.12 on 2020-02-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0026_collectionpageobjectmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpage',
            name='display_location',
            field=models.BooleanField(default=False, help_text='Display a location field from the EDM?'),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='object_identifier',
            field=models.URLField(blank=True, help_text='Use a Bib ID or a record PI to construct a link to the catalog', max_length=255),
        ),
    ]
