# Generated by Django 2.0.12 on 2020-02-20 22:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0027_auto_20200220_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPageExternalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('service', models.IntegerField(choices=[(1, 'LUNA'), (2, 'other service')], default=1, help_text='Choose an external service')),
                ('identifier', models.CharField(help_text='identifier to retrieve object from service', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='col_external_service', to='lib_collections.CollectionPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
