# Generated by Django 2.0.12 on 2020-02-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0028_collectionpageexternalservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpage',
            name='collection',
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='digital_collection',
            field=models.BooleanField(default=False, help_text='Is this a Digital Collection?'),
        ),
    ]
