# Generated by Django 2.0.12 on 2020-02-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0029_auto_20200224_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpagemetadata',
            name='page',
        ),
        migrations.DeleteModel(
            name='CollectionPageMetadata',
        ),
    ]
