# Generated by Django 2.0.12 on 2020-02-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0030_auto_20200224_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpage',
            name='search_bar',
            field=models.BooleanField(default=False, help_text='Include search bar in the side panel?'),
        ),
    ]
