# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0032_auto_20160629_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingareapage',
            name='change_to_callout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='change_to_callout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='change_to_callout',
            field=models.BooleanField(default=False),
        ),
    ]
