# Generated by Django 2.0.12 on 2020-02-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0032_remove_collectionpage_search_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpage',
            name='highlighted_records',
            field=models.URLField(blank=True, help_text='URL for browse index in IIIF to display\n            results on collection parent page'),
        ),
        migrations.AlterField(
            model_name='collectionpagesearch',
            name='default',
            field=models.BooleanField(default=False, help_text='Is this the default search? (If more than one are selected, the\n            first one selected will be the default.)'),
        ),
    ]
