# Generated by Django 2.0.12 on 2020-02-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0033_auto_20200224_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpagefacet',
            name='include',
        ),
    ]
