# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0033_auto_20160701_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingareapage',
            name='active_tag',
        ),
        migrations.RemoveField(
            model_name='collectionpage',
            name='active_tag',
        ),
        migrations.RemoveField(
            model_name='exhibitpage',
            name='active_tag',
        ),
    ]
