# Generated by Django 2.0.12 on 2020-02-24 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0034_remove_collectionpagefacet_include'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionpageresult',
            old_name='label',
            new_name='field_label',
        ),
    ]
