# Generated by Django 2.0.12 on 2020-02-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0035_auto_20200224_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpageresult',
            name='field_identifier',
            field=models.CharField(blank=True, help_text='EDM/IIIF field identifier', max_length=255),
        ),
    ]
