# Generated by Django 2.0.12 on 2020-02-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0036_collectionpageresult_field_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpage',
            name='object_identifier',
        ),
    ]
