# Generated by Django 2.0.12 on 2020-02-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0038_auto_20200224_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionpage',
            old_name='highlighted_records',
            new_name='highlighted',
        ),
    ]
