# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 17:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0038_auto_20160726_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='branding_color',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Please enter a hex color, e.g. #012043', regex='^#[a-zA-Z0-9]{6}$')]),
        ),
    ]
