# Generated by Django 2.2.10 on 2020-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0040_collectionpage_highlighted_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpage',
            name='highlighted',
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='object_identifier',
            field=models.URLField(blank=True, help_text='Use a Bib ID or a record PI to construct             a link to the catalog', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='highlighted_records',
            field=models.URLField(blank=True, help_text='URL for the select objects you would             like to show in the collection page'),
        ),
        migrations.AlterField(
            model_name='collectionpageclusterbrowse',
            name='include',
            field=models.BooleanField(default=False, help_text='Include browse term in collection sidebar?             (Featured browse)'),
        ),
        migrations.AlterField(
            model_name='collectionpagefacet',
            name='includes_ocr',
            field=models.BooleanField(default=False, help_text='Do the searchable objects have OCR?'),
        ),
        migrations.AlterField(
            model_name='collectionpagelistbrowse',
            name='include',
            field=models.BooleanField(default=False, help_text='Include browse term in collection sidebar?             (Featured browse)'),
        ),
        migrations.AlterField(
            model_name='collectionpageobjectmetadata',
            name='hotlinked',
            field=models.BooleanField(default=False, help_text='Do you want this label to linked to a unique browse view?'),
        ),
        migrations.AlterField(
            model_name='collectionpageobjectmetadata',
            name='link_target',
            field=models.IntegerField(choices=[(1, 'go to a results page for the selected item'), (2, 'link to a related item in the collection')], default=1, help_text='How do you want the link to behave?             (Required for hotlinked)'),
        ),
        migrations.AlterField(
            model_name='collectionpagesearch',
            name='default',
            field=models.BooleanField(default=False, help_text='Is this the default search? (If more than one are selected, the             first one selected will be the default.)'),
        ),
        migrations.AlterField(
            model_name='collectionpagesearch',
            name='includes_ocr',
            field=models.BooleanField(default=False, help_text='Do the searchable objects have OCR?'),
        ),
    ]
