# Generated by Django 3.0.7 on 2021-02-03 22:11

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('lib_collections', '0046_auto_20200807_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitpage',
            name='extra_exhibit_info',
            field=wagtail.fields.RichTextField(blank=True, help_text='Additional unique information for accessing exhibit'),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='exhibit_close_date',
            field=models.DateField(blank=True, help_text='Online only exhibits: Choose a date to stop featuring exhibit as "current" in browse and widgets.', null=True),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='short_abstract',
            field=models.TextField(default='', help_text='Shown in Exhibit browse view'),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='space_type',
            field=models.CharField(blank=True, choices=[('Case', 'Case'), ('Gallery', 'Gallery'), ('Online', 'Online')], max_length=255),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Shown in browse view and widgets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='thumbnail_caption',
            field=models.TextField(blank=True, default='', help_text='Optional. Displays under thumbnail if NOT a web exhibit.'),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='web_exhibit',
            field=models.BooleanField(default=False, help_text='Turns on custom styling'),
        ),
    ]
