# Generated by Django 3.0.7 on 2021-02-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0047_auto_20210203_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitpage',
            name='exhibit_close_date',
            field=models.DateField(blank=True, help_text='When exhibit stops being featured as "current." If "space type" is "Online" end date will not display.', null=True),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='exhibit_open_date',
            field=models.DateField(blank=True, help_text='Controls when an exhibit starts being featured as "current" in browse and widgets.', null=True),
        ),
    ]
