# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0049_auto_20161014_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitpage',
            name='web_exhibit',
            field=models.BooleanField(default=False),
        ),
    ]
