# Generated by Django 3.0.7 on 2021-03-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0048_auto_20210219_1036'),
        ('lib_collections', '0049_auto_20210303_0957'),
    ]

    operations = [
    ]
