# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0052_auto_20161103_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingareapage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectingareapage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='collectingareapage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectingareapage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='collectingareapage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectingareapage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectionpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectionpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_collectionpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='exhibitchildpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_exhibitchildpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='exhibitchildpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_exhibitchildpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='exhibitchildpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_exhibitchildpage_maintainer', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='content_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_exhibitpage_content_specialist', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_exhibitpage_editor', to='staff.StaffPage'),
        ),
        migrations.AlterField(
            model_name='exhibitpage',
            name='page_maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib_collections_exhibitpage_maintainer', to='staff.StaffPage'),
        ),
    ]
