# Generated by Django 3.2.15 on 2023-06-01 18:24

import base.models
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lib_collections', '0052_auto_20221208_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingareapage',
            name='link_queue',
            field=wagtail.fields.StreamField([('spreadsheet', base.models.LinkQueueSpreadsheetBlock())], blank=True, default='', help_text='Spreadsheets should be .xlsx files with the following headers: "Start Date", "End Date", "Link Text", and "URL"', use_json_field=True),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='link_queue',
            field=wagtail.fields.StreamField([('spreadsheet', base.models.LinkQueueSpreadsheetBlock())], blank=True, default='', help_text='Spreadsheets should be .xlsx files with the following headers: "Start Date", "End Date", "Link Text", and "URL"', use_json_field=True),
        ),
        migrations.AddField(
            model_name='exhibitchildpage',
            name='link_queue',
            field=wagtail.fields.StreamField([('spreadsheet', base.models.LinkQueueSpreadsheetBlock())], blank=True, default='', help_text='Spreadsheets should be .xlsx files with the following headers: "Start Date", "End Date", "Link Text", and "URL"', use_json_field=True),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='link_queue',
            field=wagtail.fields.StreamField([('spreadsheet', base.models.LinkQueueSpreadsheetBlock())], blank=True, default='', help_text='Spreadsheets should be .xlsx files with the following headers: "Start Date", "End Date", "Link Text", and "URL"', use_json_field=True),
        ),
    ]
