# Generated by Django 4.1.13 on 2024-04-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lib_collections",
            "0054_alter_collectingareapage_content_specialist_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectingareapage",
            name="news_feed_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "--------"),
                    ("library_kiosk", "Library"),
                    ("law_kiosk", "Law"),
                    ("sciences_kiosk", "Sciences"),
                    ("scrc_kiosk", "SCRC"),
                    ("cds_kiosk", "CDS"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="collectionpage",
            name="news_feed_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "--------"),
                    ("library_kiosk", "Library"),
                    ("law_kiosk", "Law"),
                    ("sciences_kiosk", "Sciences"),
                    ("scrc_kiosk", "SCRC"),
                    ("cds_kiosk", "CDS"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exhibitchildpage",
            name="news_feed_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "--------"),
                    ("library_kiosk", "Library"),
                    ("law_kiosk", "Law"),
                    ("sciences_kiosk", "Sciences"),
                    ("scrc_kiosk", "SCRC"),
                    ("cds_kiosk", "CDS"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exhibitpage",
            name="news_feed_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "--------"),
                    ("library_kiosk", "Library"),
                    ("law_kiosk", "Law"),
                    ("sciences_kiosk", "Sciences"),
                    ("scrc_kiosk", "SCRC"),
                    ("cds_kiosk", "CDS"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
