# Generated by Django 5.0.10 on 2025-05-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lib_collections",
            "0056_collectingareapage_exclude_from_search_engines_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="collectingareapage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collectionpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exhibitchildpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exhibitpage",
            name="similar_pages_in_right_sidebar",
            field=models.BooleanField(default=False),
        ),
    ]
