# Generated by Django 5.2.8 on 2025-11-10 20:21

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lib_collections",
            "0058_alter_collectingareapage_collecting_statement_and_more",
        ),
        ("staff", "0032_alter_staffpage_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExhibitPageStaffContacts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibit_page_staff_contacts",
                        to="lib_collections.exhibitpage",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibit_staff_placements",
                        to="staff.staffpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Contact",
                "verbose_name_plural": "Staff Contacts",
            },
        ),
    ]
