# Generated by Django 5.2.8 on 2025-11-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lib_collections", "0059_exhibitpagestaffcontacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhibitpage",
            name="staff_contact",
        ),
    ]
