# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0002_auto_20160328_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirectpage',
            name='sort_order',
        ),
    ]
