# Generated by Django 2.0.12 on 2019-09-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0003_redirectpage_display_current_web_exhibits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirectpage',
            name='news_feed_url',
        ),
    ]
