# Generated by Django 3.1.12 on 2022-09-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_auto_20210303_0957'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('redirects', '0007_auto_20200528_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoopRedirectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('start_sidebar_from_here', models.BooleanField(default=False)),
                ('show_sidebar', models.BooleanField(default=False)),
                ('last_reviewed', models.DateField(blank=True, null=True, verbose_name='Last Reviewed')),
                ('redirect_url', models.URLField(default='https://loop.lib.uchicago.edu/')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirects_loopredirectpage_editor', to='staff.staffpage')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('page_maintainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirects_loopredirectpage_maintainer', to='staff.staffpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
