# Generated by Django 3.2.15 on 2022-12-09 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0008_loopredirectpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loopredirectpage',
            name='redirect_url',
        ),
    ]
