# Generated by Django 4.1.10 on 2023-07-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0028_alter_staffpage_bio"),
        ("units", "0015_auto_20220311_1327"),
        ("redirects", "0010_redirectpage_link_queue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loopredirectpage",
            name="editor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_editor",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="loopredirectpage",
            name="page_maintainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_maintainer",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="redirectpage",
            name="content_specialist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_content_specialist",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="redirectpage",
            name="editor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_editor",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="redirectpage",
            name="page_maintainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_maintainer",
                to="staff.staffpage",
            ),
        ),
        migrations.AlterField(
            model_name="redirectpage",
            name="unit",
            field=models.ForeignKey(
                limit_choices_to={"display_in_dropdown": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to="units.unitpage",
            ),
        ),
    ]
