# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0013_redirectpage_change_to_callout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirectpage',
            name='active_tag',
        ),
    ]
